### ISSUE TITLE
vue-resource

### ISSUE THREAD

**Issue by duckbox** [vuejs/vue-resource#1]
Opening the discussion on this.

We are aiming for something that will be sugar for REST apis, and not necessarily different transport adaptors, REST / Socket / localStorage / Firebase etc

Roadmap states if something solid exists, use instead or build on top of. Are there any solid examples out there?

**Comment by bart** [comment]
What's the current status and what about https://github.com/pagekit/pagekit/tree/develop/vendor/assets/vue-resource?

**Comment by yyx990803** [comment]
@bart there's no official implementation at the moment. We might move pagekit's implementation here in the future.

**Comment by bart** [comment]
Kk, so I will standing by. Thanks so far!

**Comment by steffans** [comment]
@bart vue-resource 0.1.0 is now available.

**Comment by kazupon** [comment]
:+1:

**Comment by bart** [comment]
Wow, that was fast. Thanks a lot @steffans
