### ISSUE TITLE
Add to npm registry

### ISSUE THREAD

**Issue by psren** [vuejs/vue-resource#12]
Could you please add the package to npm registry?

**Comment by yyx990803** [comment]
I have published this to npm as `vue-resource`.

@steffans: let me know your npm username and I can add you as a maintainer to the package.

**Comment by steffans** [comment]
@yyx990803 Sure, my usernam is also steffans. Thanx!

**Comment by yyx990803** [comment]
@steffans done :)

**Comment by kamuran21** [comment]
@yyx990803 can you give an example code for vue-resource as required it with webpack.
I could't work it
