### ISSUE TITLE
Pulling success functionality into its own chainable method

### ISSUE THREAD

**Issue by brandonferens** [vuejs/vue-resource#13]
I would love to see the success method pulled into its own chainable method the same way that error is done. So some potential code could be:
```javascript
this.$http.get('/my-url')
    .success(function (data) {
        // success logic
    })
    .error(function (data) {
        // error logic
    });
```
In my opinion, this would clean up some slopping looking code from having a callback method as one of the parameters of the get, post, etc., methods.

**Comment by steffans** [comment]
It already works that way, currently there are three chainable methods:

```javascript
this.$http.get('/my-url')
    .success(function (data) {
        // success logic
    })
    .error(function (data) {
        // error logic
    })
    .always(function (data) {
        // always logic
    });
```

**Comment by brandonferens** [comment]
Apparently I need to read the docs better. Thanks @steffans!
