### ISSUE TITLE
Passing headers

### ISSUE THREAD

**Issue by briward** [vuejs/vue-resource#14]
Hi, 

I've been trying to pass an `authorization` header to the http request and it doesn't seem to be working. I'm not entirely sure if this is the right way to do it, perhaps you know of a way to achieve this?

```js
new Vue({

  el: '.container',

  ready: function() {

    this.fetchNode();

  },

  methods: {
    fetchNode: function() {

      this.$http.headers.common.Authorization = 'Basic YXBpOnBhc3N3b3Jk';

      this.$http.get('/node/1', function(node) {
        this.$set('node', node);
      });

    }
  },

});
```

Thanks!

**Comment by steffans** [comment]
You can set headers through the global config:

```js
Vue.http.headers.common['Authorization'] = 'Basic YXBpOnBhc3N3b3Jk';
```
or when using the $http service through the options:

```js
this.$http.get('/node/1', function(node) {
   // code ...
}, {headers: {'Authorization': 'Basic YXBpOnBhc3N3b3Jk'}});
```

**Comment by terion-name** [comment]
@steffans this is not good. If token changes?

**Comment by terion-name** [comment]
```js
Vue.http.interceptors.push((request, next) => {
    request.headers['Authorization'] =  'Bearer ' + store.state.auth.token.access_token;
next();
});
```

doesn't work (

**Comment by kamihouse** [comment]
Is there any way to remove the authorization field, or clear the `common` attribute?

**Comment by narnikgamarnikus** [comment]
How to use headers with `then` ?
I don't know, where need setting this argument ... 

By example, in this code:

```
          submitForm: function() {
            this.$http.post(this.submitendpoint, this.checkedItems).then(
               function(response){
                alert(response.data)
            }, function(error){
                console.log(this.$http.headers.common['X-CSRF-TOKEN'])
                alert(error.data)
            })
          },
```

If I try set common['X-CSRF-TOKEN'] globaly, this works, but i want to repeat this in the function. ?
How can i do  this ? 

Thanks!

**Comment by steffans** [comment]
Check out the second example here: https://github.com/pagekit/vue-resource/blob/develop/docs/http.md#example
