### ISSUE TITLE
Post as form-data

### ISSUE THREAD

**Issue by rogierverbrugge** [vuejs/vue-resource#15]
I'm trying to do a post request to a server with form-data but I can't get it to work. When I do it with postman it works, but with the $http.post it's not working. Any idea how to solve the problem?

**Comment by steffans** [comment]
All post data is send as application/json by default, if you want to send as form-data can enable this option: 
```js
Vue.http.options.emulateJSON = true;
```

**Comment by ghprod** [comment]
:+1:

**Comment by grafa** [comment]
Hi guys,

default behavior is weird. Many frameworks try to parse POST request to pairs as key=value. Sending JSON issues unexpected errors.

**Comment by sinoon** [comment]
Yeah,I also think the default behavior is werid,and there is no info warn user that.

**Comment by steffans** [comment]
I added this to the docs, see https://github.com/vuejs/vue-resource/blob/master/docs/config.md

**Comment by grafa** [comment]
Thanks, but I do still think 99% users enabled emulateJSON param so it should be default. But the docs should solve the mystery when you ask google what to do.

**Comment by zgldh** [comment]
But I want to use multipart/form-data not application/x-www-form-urlencoded.
Is there any settings I can do?

**Comment by zombeer** [comment]
I've just faced same problem.
Solved with "emulateJSON" flag in options.
`
      let options = {
        headers: {
          'Content-Type': 'application/json'
        },
        emulateJSON: true
      };
      this.$http.post(url, postObj, options)
`

**Comment by lauroguedes** [comment]
the this.$http.put(url, formData) don't work, with post work, why?

**Comment by Sangeethks** [comment]
Use post with `Vue.http.options.emulateJSON = true;`

**Comment by TAUFEEQ1** [comment]
doing all above methods still sends a url with empty parameters

**Comment by robaxelsen** [comment]
@TAUFEEQ1 same for me. @steffans can you please reopen this?

My scenario is that the endpoint expects header 'Content-Type: 'multipart/form-data', and formData as body. Sending without content-type as header config, and with formData, results in empty object as request payload. This to me sounds like a bug/issue.

Sending with content-type as header config however, results in the request payload being an object that the endpoint doesn't accept as valid. Does not seem that the formData entries are stringified before sending them as body.

'''
export function createFax() {
    return new Promise((resolve, reject) => {
        let headers = {
            'Content-Type': 'multipart/form-data',
        };
        var formData = new FormData();
        formData.append('data', 'test fax');
        formData.append('destination', '11223344');
        formData.append('pageheader', 'test header');
        formData.append('quality', 'normal');
        formData.append('subscriber_id', 111);
        Vue.http.post('api/faxes/', formData).then(() => {
        //Vue.http.post('api/faxes/', formData, { headers: headers}).then(() => {
            resolve();
        }).catch((err)=>{
            reject(err);
        });
    });
}
'''
