### ISSUE TITLE
Cannot use vue-resource with Browserify and debowerify transformer

### ISSUE THREAD

**Issue by thibaultlavoisey** [vuejs/vue-resource#16]
Hello,

I use Vue.js with Browserify and debowerify transform. It works fine but not with vue-resource :/

Code:

``` js
var Vue = require('vue');
var Resource = require('vue-resource');
Vue.use(Resource);
```

Error:

``` js
Uncaught TypeError: plugin.apply is not a function
```

If I do a `console.log()` of vue-resource the function returns an empty object.

Any idea?

Thank's :)

**Comment by norbin** [comment]
Duplicated? install as npm package.
https://github.com/vuejs/vue-resource/issues/11

**Comment by Dreampie** [comment]
I get same problem. https://github.com/vuejs/vue-resource/issues/19
