### ISSUE TITLE
Vue.http.jsonp send url error

### ISSUE THREAD

**Issue by Honghe** [vuejs/vue-resource#164]
```
Vue.http.jsonp('http://www.baidu.com/xx:yy:zz*', function (){ });
```
But it realy set rquest url is 
```
http://www.baidu.com/xx*?callback=_jsonpxxxxxxx
```
Why others after the colon disappeared.
 Bug?

**Comment by steffans** [comment]
The `:` is used for url parameter interpolation. If you provide params `{yy: 123}` the would replace `:yy` in the url, if no param is provided the `:yy` part is removed from the url.

**Comment by Honghe** [comment]
@steffans But the target url which I want to get is `http://www.baidu.com/xx:yy:zz*`, how to do?

**Comment by Honghe** [comment]
@steffans In other word，the url going to visit contains several `:`, and not need to escape.

**Comment by Honghe** [comment]
Use the parameter and solve this problem.
```
var url = 'http://www.example.com/:arg';
var arg = {arg: 'xx:yy:zz*'};
Vue.http.jsonp(url, arg, function (){ });
```

**Comment by amirrustam** [comment]
@Honghe @steffans can this issue be closed out?

**Comment by BrainMaestro** [comment]
Sorry to reopen an old closed issue, but how do i get around this? I do not need the parameter interpolation. I need to preserve the url as is. Any ideas?
