### ISSUE TITLE
Suggestion: Interceptors: get access to the current VM

### ISSUE THREAD

**Issue by kfirba** [vuejs/vue-resource#166]
Hey.

I saw the new commit of the develop branch which presents the concept of interceptors which is great.

I was thinking that in case we want to check the response and potentially respect the user based on that response we can't really do that without having to globally expose the App and bind it to the window or something. At lest we would need to do that for the router instance (which exposes the app anyways..) - I'm taking Vue-router as an example.

I think it can be really nice if the interceptors would have an access to the current VM just like the callback functions have.

**Comment by steffans** [comment]
The interceptor functions automatically bind the current vm on `this`

**Comment by kfirba** [comment]
@steffans oh great! Is there any estimated time until the release that will include the interceptors?

**Comment by steffans** [comment]
You can work with the develop version right now. Im curios for any feeback on how they work out for you. Before a 0.2 release i want to add some more tests and maybe update some config settings which might break compatibility to the current 0.1.

**Comment by kfirba** [comment]
@steffans I would be glad to test it out. I will refactor my code these days and let you know.

**Comment by deiucanta** [comment]
@steffans is this still possible in the latest release?

**Comment by deiucanta** [comment]
I want to have an interceptor that broadcasts an events to the app instance based on the status codes of the response. VueRouter creates the instance automatically so I only have access to it in the callback of `router.start()`. But then, it's too late to register an interceptor. If I register before I can't send a reference to the app instance.

The only thing that will work would be to send the entire router to the method that registers the interceptor and "hope" that the app instance will be there when needed. It doesn't seem like a robust solution to me.

**Comment by deiucanta** [comment]
You're right. In my case it's `null` because I use Vuex and the request resides in an action which is outside of any app instance.

Any idea on how to solve this?

**Comment by LinusBorg** [comment]
> The only thing that will work would be to send the entire router to the method that registers the interceptor and "hope" that the app instance will be there when needed. It doesn't seem like a robust solution to me.

Seems fine for me. The app instance *will* be available as router.app. Nothing you have to hope for.

**Comment by aguegu** [comment]
How about this feature in 2.0?
