### ISSUE TITLE
DELETE should not send a Content-Type header by default

### ISSUE THREAD

**Issue by seyhbold** [vuejs/vue-resource#170]
Hi,

many servers answer with a 4xx status when they get a body with a DELETE request.
So, I think the default should be no headers.

The fix for me was:

`Vue.http.headers.delete = {};`

Thank you very much
Regards
Ludwig

**Comment by amirrustam** [comment]
@seyhbold Are you going to make a pull request for your changes for maintainer review? Otherwise this issue can be closed out.

**Comment by steffans** [comment]
I would recommend to enable `emulateHTTP` in your case. This will send PUT, PATCH and DELETE requests with a HTTP POST and set the X-HTTP-Method-Override header. Because some don't understand DELETE request at all.

`Vue.http.options.emulateHTTP = true;`
