### ISSUE TITLE
Subdomain supported?

### ISSUE THREAD

**Issue by jenky** [vuejs/vue-resource#172]
My API using sub domain: http://api.mydomain.com. Can I get this to work with it?

**Comment by azamat-sharapov** [comment]
What is the problem you are having?

**Comment by jenky** [comment]
I don't want to use the full url every time I make a request, I found a workaround but I want to know if this was supported or not

**Comment by amirrustam** [comment]
@jenky if you problem was resolved then please close out this issue.
