### ISSUE TITLE
can't change charset with  emulateJSON

### ISSUE THREAD

**Issue by wynfrith** [vuejs/vue-resource#174]
I just need change the charset to utf-8, like this  `Content-Type: application/x-www-form-urlencoded; charset=utf-8`, but I don't find the option of this

**Comment by Hagith** [comment]
You can change Content-Type header by setting global `beforeSend` function:
```js
Vue.http.options.beforeSend = function(request) {
    request.headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8';
};
```
