### ISSUE TITLE
URL forced slash

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-resource#175]
I noticed that when the url is created the `Vue.url.options.root` and the request `options.url` will be joined together with an slash. In some occasions that slash is extra and while doesn't seem affecting the request it does open a door for possible conflicts or strange urls format. Example:

```
Vue.url.options.root = 'http://mysite.com/index.php?format=raw';
Vue.http.interceptors.push({
    request: function (options) {
            options.url = '&controller=cart';
            ...
    }
});
```
would end up requesting to 'http://mysite.com/index.php?format=raw/&controller=cart'. Notice the slash between format and controller params.

I could fix it by moving all the params to the interceptor or just ignore it, but thought commenting it here first as perhaps would be wise to leave up to the developer to add, or not, that slash.

**Comment by steffans** [comment]
Try to use the `params`option to add or change URL params:

```
Vue.http.interceptors.push({
    request: function (options) {
            options.params = Vue.util.extend(options, {controller: 'cart'});
            ...
    }
});
```

**Comment by miljan-aleksic** [comment]
That works ok, the problem is the options.url, which if I leave it empty (because setting all as params) it will still add the extra slash. This is my code so far:

```
Vue.url.options.root = 'http://mysite.com/index.php');
Vue.http.interceptors.push({
        request: function (options) {
            options.params = Vue.util.extend(options.params, {
                format: 'raw',
                task: 'cart'
                ...
            });
            options.url = '';
        }
});
```
and the final url gets as ```http://mysite.com/index.php/?task=cart&format=raw```. As you can see there is no way of getting rid of the slash before the params. Its still valid url and I will use it as it.

Perhaps there could be a check, if `options.url = false` don't attach it to root and of course don't add any slash. It would keep backward compatibility and solve this little issue.
