### ISSUE TITLE
Error with JSONP method

### ISSUE THREAD

**Issue by brunocascio** [vuejs/vue-resource#176]
Hi guys! i have a problem with `jsonp()` method.

My Code:

```
new Vue({
  http: {
    root: 'https://yts.ag/api/v2'
  },
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  },
  ready: function() {
    // GET request
    this.$http.jsonp(
      'list_movies.jsonp',
      // success
      function(data, status, request){
        console.log(data)
      },
      // fails
      function(){
        console.log('fails')
      }
    );

  }
})
```

The response is:

![screenshot from 2015-11-22 14 32 08](https://cloud.githubusercontent.com/assets/2397875/11325185/d68562f8-9125-11e5-8901-3553a0189e95.png)

But, the http response is  ok:

![screenshot from 2015-11-22 14 33 11](https://cloud.githubusercontent.com/assets/2397875/11325191/f90d4624-9125-11e5-9c61-bde2b505d348.png)

i don't understand why the `data` argument is "load".

**Comment by mmcai** [comment]
你的数据格式有问题！ response data

**Comment by brunocascio** [comment]
@mmcai i understand. thanks!

**Comment by kotazi** [comment]
I had same problem

**Comment by nick-ChenZe** [comment]
i got the same problem. This is my url `https://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/V001/?match_id=27110133&key=2B58A9C96FD73EC323CCFDA5383C4BBC` . How can i solve this? Thx

**Comment by loboweissmann** [comment]
Hi, I faced the same problem
Here is a code snippet to reproduce this bug: https://gist.github.com/loboweissmann/8dd81b37f5c804a7d5e46180f7e1e3c4

**Comment by vip30** [comment]
@loboweissmann 
Although you may solve this question already, just for your reference (or others)
Here is normal server side json output (which is represent your site [http://devall.com.br/api/posts?sort=publicacao&offset=0])
https://jsfiddle.net/yghuot5z/

And this is typically jsonp format
https://jsfiddle.net/yghuot5z/1/
If you call the server side url, you may see something like that
`_jsonpsojdnhsja29owh8e0xvoq1tt9({});`
which means client side will use this function "_jsonpsojdnhsja29owh8e0xvoq1tt9" for the callback

Server side is not matched the JSONP requirement as you may know that if we would like to use jsonp, either server side or client side will need to do something for fitting the requirement
