### ISSUE TITLE
Nested promises example

### ISSUE THREAD

**Issue by jonagoldman** [vuejs/vue-resource#178]
I think a simple example of nested promises can be helpful inside the docs.

I was expecting that something similar to the Angular $q module was needed in order to wait for nested promises, until I realized its not needed and the ```success()``` method will receive the last executed promise if the returned value for each callback is a promise.
 
In this example the ```register()``` method returns a promise that calls the ```authenticate()``` method that also returns a promise:

```js
class AuthService {

    authenticate(credentials) {
        return Vue.http.post('authenticate', credentials, function(response, status, request) {
            return response;
        });
    },

    register(credentials) {
        return Vue.http.post('register', credentials, function(response, status, request) {
            return this.authenticate(credentials);
        });
    }
}
```

So when doing something like this:
```js
AuthService.register(credentials).success(function(response, status, request) {
    // the response parameter comes from the returned value of the authenticate() method
});
```

The success() callback magically waits to the nested promise, in this case the one inside the authenticate() method.

Blown away! :)

**Comment by kirkbushell** [comment]
+1

**Comment by kirkbushell** [comment]
Any idea how to work with promise objects in that fashion within interceptors?

**Comment by JosephSilber** [comment]
Nested promises already work. Use .then() instead of .success().

**Comment by kirkbushell** [comment]
I know, but within interceptors I'm getting some serious weirdness.

**Comment by JosephSilber** [comment]
The code posted passes a callback to the post method. That does not wait for the promise chain to complete.

**Comment by kirkbushell** [comment]
I'm not asking about the code above, I couldn't care less about it. The question is how do you get promise objects working within vue-resource interceptors? Subsequent interceptors for me end up with an undefined response.

**Comment by steffans** [comment]
@kirkbushell Make sure to return the request/response object in your interceptor function.

```
    return {

        request: function (request) {
            // code ...
            return request;
        },

        response: function (response) {
            // code ...
            return response;
        }

    };
```

**Comment by kirkbushell** [comment]
I have to use promises (I think) because my interceptors are doing their own API calls. In this example, they're refreshing JSON web tokens whenever auth fails. So, there is at least 2 additional calls once a 401 is made:

1. Request a fresh JSON web token
2. Retry the request that failed

It fetches the jSON web token, and all that works, but the step after fails because the interceptor is also trying to work with these other calls.

**Comment by jonagoldman** [comment]
@JosephSilber the code posted does in fact wait until the last promise chain is resolved, that's what all this post is about. The register() method triggers a chain of two promises, the response it receives is in fact the result of the last promise resolve. Where is that magic happening I have no idea, and again, that's what all this post is about.

**Comment by JosephSilber** [comment]
@jonagoldman oh! I see [it's been changed to defer to `then`](https://github.com/vuejs/vue-resource/blob/master/src/promise.js#L84) and it's been deprecated.

Before that it was its own thing, and it didn't wait for nested promises to resolve.
