### ISSUE TITLE
Resend request or retry

### ISSUE THREAD

**Issue by znck** [vuejs/vue-resource#181]
How to resend a request from interceptor?

Ex:
```
get /some/resource => response status = 401, wait for auth
post /auth/login 
on auth => retry /some/resource
```

**Comment by jorgemurta** [comment]
+1

**Comment by kirkbushell** [comment]
I've been able to get requests happening within, and re-sends. However, I'm having problems with working with Promises within that layer. The docs on vue-resource in this area need some work, as I'm bumbling through atm - but catching and re-sending seems relatively straight-forward.

This is exactly the problem I'm currently working on, btw - if a JSON web token expires, I want to catch that response, refresh the token, then re-send the request that failed. However, I'm getting all sorts of issues to do with promises and the exceptions thrown within vue/vue-resource aren't helping.

**Comment by MECU** [comment]
@kirkbushell Would you please you share how you are catching and re-sending requests?

**Comment by kirkbushell** [comment]
Cache the original request, make a new one, then re-send the previous one by looking at response.request.

**Comment by kirkbushell** [comment]
I did something like:

```javascript
function (response) {
    var original = response;
   
    return Vue.http.get('/auth/refresh').then(function() { return Vue.http[original.method](original.params); });
```

**Comment by nivv** [comment]
@kirkbushell I'm having thesame problem, however when I do ` Vue.http[original.method](original.params)` nothing happens. Care to show a little more code how you've structured it?

**Comment by kirkbushell** [comment]
@nivv are you sure it's being executed? This is the exact callback I'm using in my code. If you're unsure, investigate the response object.

**Comment by nivv** [comment]
@kirkbushell I think I commented on your gist as well. It works now, but it won't set data on the VM after the request succeeds. The request has the data, but it won't set it.

You can see my comment here: 
https://gist.github.com/kirkbushell/6b60a44c0949d08feb46
