### ISSUE TITLE
Use Vue.http or Vue.resource standalone?

### ISSUE THREAD

**Issue by panzhangwang** [vuejs/vue-resource#188]
Any suggestions to use Vue.http or Vue.resource standalone? I want to keep the project less bloated.

**Comment by steffans** [comment]
You mean you want to use Vue.http and Vue.resource without Vue library itself? If so im sorry, right now this is not supported.

**Comment by panzhangwang** [comment]
I want use Vue and may need Vue.http only. Some might use Vue.resource only.

**Comment by panzhangwang** [comment]
I might be wrong. but is there a way to have Vue,http and Vue.resource services separately.

**Comment by steffans** [comment]
The Vue.http is biggest part of the plugin. The Vue.resource service just an small layer on top of it.
