### ISSUE TITLE
gulp-webpack  Uncaught TypeError: plugin.apply is not a function

### ISSUE THREAD

**Issue by Dreampie** [vuejs/vue-resource#19]
```javascript
Resource = require 'vue-resource'
Vue.use Resource
```

**Comment by Dreampie** [comment]
![image](https://cloud.githubusercontent.com/assets/3667080/8623702/7e43b61e-2765-11e5-80e0-332bdfbc7163.png)

npm  install  vue-resource

require('vue-resource')

**Comment by Dreampie** [comment]
![image](https://cloud.githubusercontent.com/assets/3667080/8632389/5eef21e8-27cb-11e5-8abc-be86e2062936.png)

**Comment by Dreampie** [comment]
only  use  webpack  it's ok,use gulp-webpack get this error

**Comment by steffans** [comment]
@Dreampie Can you try again with v0.1.7? I added a universal module definition in the dist versions.

**Comment by Dreampie** [comment]
it's ok,about vue-router, can you help me?
