### ISSUE TITLE
Does there a request method like promise all?

### ISSUE THREAD

**Issue by pannz** [vuejs/vue-resource#194]
Does there support  a get method like:
```javascript      
this.$http.all('request_url_1', 'request_url_2' [,]).then(data){
           //data[0]  is res_of_request_1
           //data[1]  is res_of_request_2
}  
```
？

**Comment by JosephSilber** [comment]
You should use `Promise.all` for this:

```js
Promise.all([this.$http.get('request_url_1'), this.$http.get('request_url_1')]).then(function(data) {
    // data[0]  is res_of_request_1
    // data[1]  is res_of_request_2
});
```

**Comment by dionisnote** [comment]
You can use 
```
this.$promise.all([
    this.$http.get('url1'),
    this.$http.get('url1')
]).then(function(responseArr){

});
```
https://github.com/pagekit/vue-resource/blob/develop/src/promise.js#L22

**Comment by alonprince** [comment]
@dionisnote 
In my code, `this.$promise.all` is not working.Got an error: `this.$promise.all is not a function`.`this` not bind to a wrong object.I don't know why.

**Comment by dionisnote** [comment]
@alonprince It works only if you use [vue-resource](https://github.com/pagekit/vue-resource)
But in last time everybody just use [axios](https://github.com/mzabriskie/axios)

**Comment by alonprince** [comment]
@dionisnote 
Yes, I am using `vue-resource^2.2.6`.

**Comment by dionisnote** [comment]
@alonprince 
https://github.com/pagekit/vue-resource/blob/develop/package.json#L3
Hmm, current stable version is 1.3.1

**Comment by alonprince** [comment]
@dionisnote 
I'm so sorry.I just look for the wrong line which records the version info of Vue.
The `vue-resource` I used is `1.3.1`now.😂

**Comment by dionisnote** [comment]
Thats true, it doesn't work now... Anyway you can use promise constructor function, like [this](https://codepen.io/dionisnote/pen/GmdRLv?editors=1111)
