### ISSUE TITLE
How to use this to set up Access-Control-Allow-Origin in headers?

### ISSUE THREAD

**Issue by snowffer** [vuejs/vue-resource#195]
I want to visit get data from another website. Do I need to  set up Access-Control-Allow-Origin? And how should I do that?

**Comment by sqlwwx** [comment]
Vue.http.options.xhr = {withCredentials: true}

**Comment by amirrustam** [comment]
@snowffer if your question was answered then please close out this issue.

**Comment by jan-wong** [comment]
@sqlwwx but there are some problems in phone.....
