### ISSUE TITLE
TypeError: this.$set is not a function

### ISSUE THREAD

**Issue by dokicro** [vuejs/vue-resource#196]
Hi I am geting this error:
**Uncaught (in promise) TypeError: this.$set is not a function**

And here is the code:

         export default {
            data: function() {
                return { movies: '' }
            },
    
            ready: function() {
                this.showMovies()
            },
    
            methods: {
                showMovies: function() {
                     this.$http.get(config.api.url + '/movies').then(function (response) {
                        this.$set('movies', response.data)
                     })
                 }
            }
         }

**Comment by dokicro** [comment]
Solved by:

this.$http.get(config.api.url + '/movies/geners', function(geners) {
                    this.$set('geners', geners)
                 })

**Comment by amirrustam** [comment]
@dokicro Referring to your original post, you are referring to the wrong `this` within the promise. You need to cache the outer scope `this` for use with in the function. Like so:

```javascript
        methods: {
            showMovies: function() {
                 var _this = this;
                 this.$http.get(config.api.url + '/movies').then(function (response) {
                    _this.$set('movies', response.data)
                 })
             }
        }
```
Since this is issue is solved, then please close it. Thanks.
