### ISSUE TITLE
vue-resource invokes the error when refresh page quickly

### ISSUE THREAD

**Issue by benchan2015** [vuejs/vue-resource#199]
The page uses vue-resource to get data ,like this:
 this.$http.get(config.activityApi + 'activity/activityInterface/getActivityByDay.do', {
                day: day,
                storeId: util.getQueryString('nodeCode')
            }, function(data, status, request) {
               //successfully
            }).error(function(data, status, request) {
                dialog.showTip('The network error occurred,please try it again');
                dialog.hideLoading();
            });
when i refresh the page quickly in a second ,the error function will be invoked,could you tell me how to fix it,looking forward to your reply.

**Comment by amirrustam** [comment]
@benchan2015 this is not sufficient information to assist you. Also this issue does not conform to the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines). Please **close this issue** and **clearly ask your question** within in the [community forums](http://forum.vuejs.org) where many people will be glad to help you out. Thanks.

**Comment by dengjianan** [comment]
how to refresh data, while router changed
