### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by kacpersaw** [vuejs/vue-resource#2]
When I add require('vue-resource') line my code then i got Vue is not defined in console.

**Comment by kacpersaw** [comment]
Problem still exists.

I'll show you what i'm doing:
1. git clone https://github.com/vuejs/vue-browserify-example
2. I'm changed in package.json vue branch to 0.12.0-beta
3. enter to vue-browserify-example and run `npm install`
4. enter to node_modules dir
5. git clone https://github.com/vuejs/vue-resource.git
6. npm run prod in vue-resource dir
7. vue-browserify-example/src/main.js looks like this:
```js
require('insert-css')(require('./app.css'));

var Vue = require('vue');

var vueResource = require('vue-resource');
Vue.use(vueResource);

new Vue({
    el: 'body',
    template: require('./app.html'),
    data: {
        title: 'Hello Browserify & Vue.js!'
    },
    methods: {
        onClick: function (e) {
            this.$http.get('http://echo.jsontest.com/key/value/one/two', function (data, status, request) {
                console.log(data);
            }).error(function (data, status, request) {
            });
        }
    }
});
```  
8. In my html I have button `<button v-on="click: onClick">Trigger a handler</button>`  
9. After this I ran `npm run dev`  
10. When I open this in my browser in dev console i got: 
```js
Uncaught ReferenceError: Vue is not defined
/home/kacper/Projects/vue/vue-base/node_modules/vue-resource/src/util.js
s
(anonymous function)
install
exports.use
/home/kacper/Projects/vue/vue-base/src/main.js../app.css
s
e
(anonymous function)
```

**Comment by steffans** [comment]
@kacpersaw Try again, i update the code so `window.Vue` is not required to be a global.

**Comment by kacpersaw** [comment]
@steffans Now it's working. Thanks :)

**Comment by mnzt** [comment]
Going to resurface this.

Getting thrown `Uncaught TypeError: Cannot read property 'get' of undefined` from the following code, running through browserify.

```
var Vue = require('vue');
var VueResource = require('vue-resource')

Vue.use(VueResource);

new Vue({
  el: '#app',
  ready: () => {
    this.$http.get('/api/token', (data, status, request) => {
        console.log(data);
        this.$set('token', data)
      })
      .error((data, status, request) => {

      })
  },
})

```

**Comment by azamat-sharapov** [comment]
@mnzt you don't need double arrow for `ready` hook.

**Comment by mnzt** [comment]
@azmat-sharapov 

Lexical `this` binding, how could I forget?! Thank you.
