### ISSUE TITLE
Issue with callback execution after upgrading to 0.1.6

### ISSUE THREAD

**Issue by orestisioakeimidis** [vuejs/vue-resource#20]
Hi,

I have an issue with callback execution after upgrading to 0.1.6 or 0.1.7.

When I am receiving a BAD REQUEST from the server instead of the error callback to be executed, the success callback does. Can anyone else confirm this?

Thanks in advance!

**Comment by steffans** [comment]
@orestisioakeimidis It is fixed in v0.1.8
