### ISSUE TITLE
Uncaught ReferenceError: resource is not defined

### ISSUE THREAD

**Issue by stefkosmo** [vuejs/vue-resource#202]
Trouble using: 
<pre>var resource = this.$resource('api/tasks/{id}');</pre>
When not used within method directly.

<pre>Vue.component('tasks', {
	template: '#tasks-template',

	data: function() {
		return {
			list: []
		}
	},

	ready: function() {
		var resource = this.$resource('api/tasks/{id}');

		this.fetchTaskList();
	},

	methods: {

		deleteTask: function(task) {
			this.list.$remove(task);
		},

		fetchTaskList: function() {
			resource.get().then(function(tasks) {
				this.$set('list', tasks.data)
			});
		}
		
	}
	
});

new Vue({
	el: 'body',
});</pre>

returns error of : <b>Uncaught ReferenceError: resource is not defined</b>

**Comment by azamat-sharapov** [comment]
`ready` and `fetchTaskList` are 2 different methods. `fetchTaskList` has no idea about `resource` variable, until you define it in `fetchTaskList`.

**Comment by stefkosmo** [comment]
Ahhhh I see, using a similar formula above how could I make var resource global, so I don't have define it in every method that requires it?

**Comment by azamat-sharapov** [comment]
just assign it in the top of the file, outside of any function..

**Comment by stefkosmo** [comment]
But if I do that then $resource will not be defined?

**Comment by azamat-sharapov** [comment]
```
var resource = Vue.resource('api/tasks/{id}');
```

**Comment by stefkosmo** [comment]
Amaze.
