### ISSUE TITLE
how to get the cookie 

### ISSUE THREAD

**Issue by ramstein74** [vuejs/vue-resource#204]
Hi,  my server responds with a cookie but i cannot see it in the responde object.
How can i see it ?

**Comment by amirrustam** [comment]
Is your server sending an [HttpOnly](https://www.owasp.org/index.php/HttpOnly) cookie?

Also in the future please ask these types of questions within the [community forums](http://forum.vuejs.org) first. Then if the discussion within the forum reveals a bug or potential enhancement to the project, you can create an issue. Thanks.

**Comment by ramstein74** [comment]
yep httponly.
Thank you
solved

**Comment by Slgoetz** [comment]
What was the solution!!
