### ISSUE TITLE
Usage of deprecated methods

### ISSUE THREAD

**Issue by sztrzask** [vuejs/vue-resource#209]
Vue resource is using now deprecated success and error instead of then and catch in promises

**Comment by Centaur** [comment]
:joy: This should be in Readme.md, with some sample code.

**Comment by nacr-dev** [comment]
+1

**Comment by steffans** [comment]
Yes, as mentioned in the changelog the success/error methods are deprecated (since 0.50) and will be removed in future versions. The readme and [docs](https://github.com/vuejs/vue-resource/blob/develop/docs/http.md) are also updated.
