### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by amine014** [vuejs/vue-resource#21]
Hi,

Everything is ok in chrome, and FF (I tried it quickly) but with IE it's not working and I got this message (translated from french).

SCRIPT5007: Impossible to define « success » proprety of a null or undefined reference

Here's my code (I'm using it with Laravel) : 

Vue.http.headers.common['X-CSRF-TOKEN'] = document.querySelector('#token').getAttribute('value');

new Vue ({
    el: '#loginForm',

    data: {

        loginRequest : {
            email: '',
            password:''
        },
        email_txt:'Username / email',
        password_txt:'Mot de passe',
        error: ''
    },

    methods: {
        onSubmitForm: function(e) {
            e.preventDefault();
            this.$http.post('auth/login', this.loginRequest, function (errors) {

                alert(  JSON.stringify(errors) + "\nStatus: " + status);

                if (errors) {
                    if (errors.email) {
                        if (errors.email) {
                            this.email_txt = errors.email
                        }
                        if (errors.password) {
                            this.password_txt = errors.password
                        }
                    }
                    else (alert('couple pas bon!'))
                }
                else {
                
                location.reload();
                }
            }).error(function (data, status, request) {
                alert('error')
            })

        }
    }

});

**Comment by amine014** [comment]
Any help please ?

**Comment by JosephSilber** [comment]
Try using the then callback instead of passing the callback directly.

...get(...).then(function(response) { /* use response.data */ });

**Comment by amine014** [comment]
Thank you Joseph for the answer, But I'm not sure that I understand it, The probleme I have with IE is that even if I do this : -----> this.$http.post('auth/login') <------i'll have the same error message. It's not recognizing I think (this.$http) I tried (VUE.HTTP) too :(

**Comment by nteath** [comment]
I just came across the same issue. Any help would be appreciated

**Comment by amine014** [comment]
It's making me fool !!  nteath if you find any solution please share it

**Comment by nteath** [comment]
I tried what @JosephSilber suggested but with no luck. He suggested instead of passing a callback function as the third argument in the post function, you can do something like the following:

this.$http.post('url', data).then(
    function(response) {
        // do something
     }
);

**Comment by amine014** [comment]
I'm trying jQuery now, and it works even with CSRF:

$.ajax({
                method: "POST",
                url: "auth/login"+ '?_token='.concat(document.querySelector('#token').getAttribute('value')),
                data: { email: this.loginRequest.email, password: this.loginRequest.password }
            })
                .done(function( msg ) {
                    alert(  msg );
                });

**Comment by nteath** [comment]
Ok good to know, i had it previously with jquery but never tested it on IE.

**Comment by amine014** [comment]
nteath you're working for a personal project or you're developer ?

**Comment by nteath** [comment]
@amine014  It's a simple personal project for now. I just want to get familiar with vue for now

**Comment by JosephSilber** [comment]
@amine014 @nteath which version of `vue-resource` are you using?

I tried this in IE11 on Windows 7 and it worked as expected.

---

> The problem I have with IE is that even if I do this: `this.$http.post('auth/login')` i'll have the same error message.

@amine014 that doesn't really ring right. Can you paste the actual error you're getting, in French?

**Comment by nteath** [comment]
I just updated to v0.1.8 and the issue seems to be resolved. I am testing on Windows & IE 11.
