### ISSUE TITLE
Bug about root options

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-resource#211]
my site is `http://bbb.com`

I set up root options first link this:
```javascript
import Vue from 'vue'
import Resource from 'vue-resource'

Vue.use(Resource)

Vue.http.options.root = 'http://aaa.com'  // api server domain
```

then I use `Vue.http` to get response like this:
```javascript
export default {
    getIndex ({data, success, error}) {
        // it will get `http://aaa.com/shop/keyword`, works well
        Vue.http.get('shop/keyword', data).then(success, error)
    }
}
```

it's work, but when I start url from `/` it's error
```javascript

export default {
    getIndex ({data, success, error}) {
        // it will get `http://bbb.com/shop/keyword`, works error
        Vue.http.get('/shop/keyword', data).then(success, error)
    }
}
```

could u fix it?

**Comment by steffans** [comment]
This is the intended behavior, only relative urls are extended with the `Vue.http.options.root`option. Every absolute url starting with `/`or `http` will not be modified.

**Comment by fobdy** [comment]
I think if `root` url is set, it doesn't matter if there any `/` prefix. So `/path` have to be joined like a path join function does.

**Comment by azamat-sharapov** [comment]
I would say this is feature, not bug. What if you wanted to bypass root domain for single request in huge codebase? Also, this somehow feels natural for me, browser handles paths same way for files (HTML/CSS/JS) for example.

**Comment by fobdy** [comment]
If root doesn't have some domains in it but just paths maybe it's right and natural. But for external hosts it's not so clear. Maybe i'm wrong

**Comment by fobdy** [comment]
Maybe we don't need a root at all or need some factory to populate different preconfigured instances (like resources). It seems too complicated so for now we can leave it as is

**Comment by jaesung2061** [comment]
I think maybe there should be an option to force overrides? I have a server that's providing a REST interface, but I'm using webpack dev server. So I can't make requests like `/api/users` which will send it to `localhost:8080/users/1` instead of `myapp.dev/api/users`.
