### ISSUE TITLE
Response Object always have '0' on status

### ISSUE THREAD

**Issue by odranoelBR** [vuejs/vue-resource#212]
Hello ppl.

Im getting status code 0 on any  HTTP error. On chrome network tab says 409, 422 but the object come whit the wrong status. 
Tks !

Code: 

<pre>  this.$http.post('http://localhost/sigmapi/public/api/' + this.apiName, {nome: this.novoNome})
                .then(function (response) {
                    this.dados.push(response.data['data'])
                    this.novoNome = ""
                    swal({
                        title: "Criado",
                        text: "Você criou a configuração <span style='color:#F8BB86'>" + response.data['data'].nome + "<span>",
                        html: true,
                        type: "success"});
                }, function (response) {
                    if(response.status == 409){
                        var errorMsg = "Desculpe, mas a configuração " + this.novoNome + " já existe.";
                    }
                    if(response.status == 422){
                        var errorMsg = "O nome da nova configuração não pode ser vazio."
                    }
                    swal("Erro", errorMsg, "error");
                });

**Comment by odranoelBR** [comment]
I understand my problem. It was CORS not enable for http 400 family.
Tks all

**Comment by rongself** [comment]
@odranoelBR excuse me，could you tell me how you fix this problem？thank you!

**Comment by odranoelBR** [comment]
Hi @rongself !
This problem comes from the API / WebService you tryng to request.

Take a read in https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

You must enable cross realm on your API. 

1. The browser willl make an HTTP OPTION before the real request
2. In this OPTION response will be present all the headers the API accept.
![image](https://cloud.githubusercontent.com/assets/7774534/22996105/b084f6e8-f3b4-11e6-8831-8b78fa4d77d2.png)
This photo resonse says the API 'allow' this HTTP methods , aceppt no ranges etc
3. So on your API enable everything you want.

You building the API or using third ?

**Comment by rongself** [comment]
@odranoelBR 
Thank you! this is a lot of help for me , I am building the API use Laravel,this is the code i set the response header:
```php
/**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $response = $next($request);

        $httpOrigin = $request->header('Origin');
        if ($httpOrigin && in_array($httpOrigin, explode(',', env('CORS_DOMAINS')))) {

            $response->header('Access-Control-Allow-Origin', $httpOrigin);
            $response->header('Access-Control-Allow-Credentials', 'true');
            $response->header('Access-Control-Expose-Headers', 'Authorization');//允许服务器接收指定的客户端发送过来的自定义header

            if($request->getMethod() === Request::METHOD_OPTIONS){
                $response->header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, DELETE');
                $response->header('Access-Control-Allow-Headers', 'Authorization');//允许浏览器发送指定的自定义header
            }

        }

        return $response;
    }
```
so now the thing i need to to is set `Public` and `Allow` these response headers right?

**Comment by rongself** [comment]
I understand my problem,i stop the laravel framework when login failed:
```php
abort(Response::HTTP_UNAUTHORIZED,$e->getMessage()); 
``` 
i think this will break the response,so i change it to :
```php
return Response::create($e->getMessage(),Response::HTTP_UNAUTHORIZED);
```
now it work , thanks you and have a nice day

**Comment by githubmann** [comment]
@rongself excuse me, i have some problem,I am front web dev , and back end framework is laravel. In some  
phone(wechat 6.5.6,andorid 6.0, honor 7) will arise status that is 0.  And Exclusion of cross-domain problem.
can you help me?
