### ISSUE TITLE
Promise is not rejected when offline

### ISSUE THREAD

**Issue by sztrzask** [vuejs/vue-resource#213]
When offline, promise is resolved and not rejected.

When status < 200 or status > 300 promise is resolved and not rejected.

**Comment by steffans** [comment]
See https://github.com/vuejs/vue-resource/blob/master/src/http/client/index.js#L30
This checks the status and set the `response.ok` property which later will reject the promise if is set to false.

What status do you get when offline?

**Comment by antoniopaisfernandes** [comment]
Check this is it suits you:

http://stackoverflow.com/questions/133925/javascript-post-request-like-a-form-submit
