### ISSUE TITLE
Strange issue with json data

### ISSUE THREAD

**Issue by Mat-Moo** [vuejs/vue-resource#214]
I have a simple json file, can be seen http://squid.live/folders.json when I load this in
```
this.$http.get('/folders.json').then(
            // success
            function (response) {
                // use response.data to populate the assets and folder structure
                console.log(response);
                this.folders = this.unflatten(response.data);
            },
            // failure
            function (response) {
                alert('Failed to load folders.json');
            });
```
 any item with a parentId of 0 then has an id of undefined?! 
If I change id to something else then it seems fine. Am I missing something with tracking or the likes? (Vue 1.0.16, resource 0.7.0)

**Comment by Mat-Moo** [comment]
Noting, if I use  Vue.http.get and console log the response then the data is as expected... until I try and do anything with it, e.g. add var that=this then that.folders = that.unflatten(response.data);

**Comment by steffans** [comment]
Is it maybe an issue with the `unflatten` function that handles the `0` parents wrong ?

**Comment by Mat-Moo** [comment]
Nope, the console log shows the data as wrong

**Comment by Mat-Moo** [comment]
It was a stupid computed var!!

```
            var result = this.folders.filter(function(obj) {
                return obj.folderID = that.activeFolder;
            })[0];

```
Spot the missing =!! Sorry for wasting your time :(
