### ISSUE TITLE
List Query Bug

### ISSUE THREAD

**Issue by akamos** [vuejs/vue-resource#217]
Hi,

I don't know really if I'm doing it right, but if I want to send a list of numbers to an address with a created resource like following:

`this.$resource('/api/statistics{/id}/').get({'id':2}, {'fields:[1,45,23]};`

then it creates following url request: 

`/api/statistics/2/?fields[]=1&fields[]=45&fields[]=23`

Why are there scopes behind the 'fields' query parameter? Is that correct or not correct behaving?

**Comment by steffans** [comment]
When you are using the `get` action the `fields` parameters will be url encoded. If use the `save` action which sends a `post` request to the server your parameters will JSON encoded. You can add you own action or modify the `get` action to use a `post` request.

**Comment by akamos** [comment]
Yes I already understood, that works great. But why are there brackets ('[]') behind the get parameters? Is that a bug or feature?

**Comment by steffans** [comment]
It's a feature with the brackets PHP will automatically create an array with all the values submitted for `fields`. With [URI templating](https://medialize.github.io/URI.js/uri-template.html) you can convert the fields into a comma separated string.

`this.$resource('/api/statistics{/id}/{?fields}').get({'id':2}, {'fields:[1,45,23]};`

will turn into:

`/api/statistics/2?fields=1,45,23`
