### ISSUE TITLE
Cross-Origin Request

### ISSUE THREAD

**Issue by raleePixel** [vuejs/vue-resource#22]
Hi,

Does anyone knows how to do a http:post via Vue-resource from a different domain?

Thanks in advanced!

Cheers
Ralee

**Comment by steffans** [comment]
You can do it with a normal post `$http.post('http://domain.com/')`, however the domain must support CORS. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by kenberkeley** [comment]
>* Backend server should set `Access-Control-Allow-Origin` to `*` or `[ Frontend server domains whitelist ]`
>* `Vue.http.options.xhr = { withCredentials: true }` is **not needed.**
>* `url` must begin with `http(s)://`. e.g. `localhost:8080` would fail.
