### ISSUE TITLE
How to get response header with vue-resource?

### ISSUE THREAD

**Issue by libertyAlone** [vuejs/vue-resource#222]
does it have api like 
`$.ajax({
        url: '/api',
        type: 'post',
        dataType: 'json',
        data: data,
        success:function(data,status,xhr){
          var a = xhr.getResponseHeader('token')); 
        }
      })`
it seems unlikely to get responseHeader in promise.then(cb) resolve callback

**Comment by steffans** [comment]
Please take a look at the second example, here: https://github.com/vuejs/vue-resource/blob/master/docs/http.md

**Comment by aios** [comment]
cant get authorization token on header with response.
