### ISSUE TITLE
can't replace string in PUT method

### ISSUE THREAD

**Issue by nannan9507** [vuejs/vue-resource#226]
First of all , thanks for share this compenent !
So, let's start. In my prctice project, I request a url like this:  $http.put('/api/user/order/{uuid}/'); 
but I can't get the value of 'uuid' in the url.
My manager use a clever way to resolve it: 
$http.put(apiMap('/api/user/order/{uuid}/').replace('{uuid}', this.uuid), {
   status: this.add.status,
   note: this.add.note
},
it can works! But I think it's not a best way to resolve it.
I can't find anything about the put methods waning in the document, so I put a issued to ask.
Thanks for answering.

**Comment by steffans** [comment]
It will also work when passing the uuid with `params` option.

```js
$http.put('/api/user/order/{uuid}/', {...}, {params: {uuid: 123}});
```
