### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by mlanin** [vuejs/vue-resource#227]
Source:
```javascript
import Vue from 'vue' // 1.0.17
import VueResource from 'vue-resource' // 0.7.0

Vue.use(VueResource)

Vue.http.options.root = config.api.base_url
```

After reload I'm getting an error:
```
Uncaught TypeError: Cannot read property 'options' of undefined
```

`console.log` shows that `Vue.http` is `undefined`.

What am I doing wrong?

**Comment by zyf0330** [comment]
`Vue.use(VueResource)` makes Vue.http exist, so you can check `import VueResource`

**Comment by mlanin** [comment]
Very strange, but it started working by itself! I swear I didn't change anything, but now it is working ))
So I'm closing the issue
