### ISSUE TITLE
why the request method is OPTIONS ?

### ISSUE THREAD

**Issue by V-Tom** [vuejs/vue-resource#228]
[issues:44](https://github.com/vuejs/vue-resource/issues/44)
[issues:47](https://github.com/vuejs/vue-resource/issues/47)

someone says:
**OPTIONS is always fired first if you're not sending requests to the same domain, so if you're server is not handling OPTIONS or doesn't have proper allow origin settings there, the GET/POST will never be sent.
It's not a bug, it's how CORS works. You would see the same thing if using angular/react or any other AJAX framework.**

but on my Node.js server. I put my server set to open cdn. it does not work.

my Node server on port 4000,i use webpack on port 8080

whatever.it will have a OPTIONS method request .

how can i resolve it?

Thanks!

**Comment by V-Tom** [comment]
![2 1](https://cloud.githubusercontent.com/assets/8033489/13448270/91c1f54c-e05c-11e5-90b3-a03855c01e43.png)
![1 1](https://cloud.githubusercontent.com/assets/8033489/13448273/9559fc2c-e05c-11e5-8f36-187393f6b142.png)

**Comment by steffans** [comment]
The OPTIONS request is part of the of the CORS spec. They are not happening when your request meets the requirements of a _Simple request_, please see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests

**Comment by V-Tom** [comment]
Thanks.
Through this issues I have learned a lot
