### ISSUE TITLE
How to set headers?

### ISSUE THREAD

**Issue by arthurkirkosa** [vuejs/vue-resource#231]
```js
Vue.http.headers.common['Content-Type'] = this.file.type;
Vue.http.headers.common['Content-Range'] = `bytes 0-${file.size - 1}/${file.size}`;

this.$http
        .put(this.ticket.upload_link_secure, file)
        .then(this.uploadSuccess, this.uploadFail);
```

Doing this will set the headers globally and I need to delete some on another request

**Comment by nblackburn** [comment]
```javascript
.put(url, data, {
    headers: {
        Authorization: 'Basic dXNlcjpwYXNzd29yZA=='
    }
})
```

The http methods take a third argument that allows youspecify headers to send along with the request, i hope this helps.

**Comment by arthurkirkosa** [comment]
If I do that the response for the PUT is 200, but the failed promise fires.

**Comment by arthurkirkosa** [comment]
@steffans indeed help wanted :) ... where's the help?

**Comment by ezeev** [comment]
I'm seeing the promise fail here as well. help wanted.

**Comment by adelriosantiago** [comment]
I don't see the 'Authorization' header being appended. I'm using this structure:

```
this.$http.get('URL' + item.route, {}, {
          headers: {
            'Authorization': 'Basic a3Rt...MzQ='
          }
        }).then(response => {
          console.log('response', response)
        })
```

What I'm doing wrong?

**Comment by adelriosantiago** [comment]
Ohh never mind about the last question. Silly error, I was sending the header in the wrong parameter.

The correct call should be:

```
this.$http.get('URL', {
          headers: {
            'Authorization': 'Basic a3Rt...MzQ='
          }
        }).then(response => {
          console.log('response', response)
        })
```

Thx.

**Comment by jhonatanfaber** [comment]
What is the difference between setting the header within the get request: 
`
this.$http.get('URL', {
          headers: {
            'x-access-token': 'XYX'
          }
        }).then(response => {
          console.log('response', response)
        })
`

and setting the header using interceptors

`Vue.http.interceptors.push((request, next) => {
  var accessToken = "XYX"
  request.headers.set('x-access-token', accessToken)
  next()
})
`
