### ISSUE TITLE
root parameter ignored on requests

### ISSUE THREAD

**Issue by PierBover** [vuejs/vue-resource#233]
So I added this to my main.js

`Vue.http.options.root = 'http://api.domain.com';`

And doing requests like this in a component:

`this.$http.get('/users').then( etc`

But calls are being made on `localhost` instead of the defined server in the `root` parameter.

Am I missing something?

**Comment by azamat-sharapov** [comment]
Remove leading slash from your request path.

**Comment by PierBover** [comment]
That did it, thanks @azamat-sharapov
