### ISSUE TITLE
Bug: POST with data in it fails a lot

### ISSUE THREAD

**Issue by snowffer** [vuejs/vue-resource#236]
If use JQuery:

```
$.post(url,{value:someData},
       function(data,status){
       console.log("\nData: " + data + "\nStatus: " + status);
});
```

This successes every time. And I can get the right data from back-end server.

But if I use this:

```
this.$http.post(url, {value:someData}).then(function (response) {
                      
 }, function (response) {
                        
 }
);
```

Almost failed every time. And I can NOT even get the data from back-end server.

url is the url I want to send. someData is the data I want to send.

**Comment by perkola** [comment]
Why does it fail? What errors are logged in the console and what is the response from the server?

**Comment by steffans** [comment]
Make sure your server can work with `application/json` requests, see https://github.com/vuejs/vue-resource/blob/master/docs/config.md#legacy-web-servers
