### ISSUE TITLE
How i can get response headers in interceptor?

### ISSUE THREAD

**Issue by aios** [vuejs/vue-resource#241]
subj.

sorry for spam...

**Comment by nblackburn** [comment]
Would it be possible if you could close this if it's no longer an issue?

**Comment by aios** [comment]
That no solved.

**Comment by nblackburn** [comment]
Ahh my apologies, well you could try this...

```javascript
Vue.http.interceptors.push({
    request: function(request) {
        console.log(request.headers);
    }
});
```

**Comment by aios** [comment]
Yep - but not get it.

**Comment by nblackburn** [comment]
You don't understand or you don't get any headers?

**Comment by aios** [comment]
I make a request to backend with JWT Auth. So i want refresh token on backend side and set Authorization header to Bearer `newtoken`
When i return response, in devtools - i have check newtoken - with vue-resource - no Authorization header in interceptor and no in code

**Comment by aios** [comment]
I solve another way - with set new token in response.data - but i want set in header and get it with vue-resource - to update JWT in interceptor.

**Comment by nblackburn** [comment]
I thought that might be where you were going wrong, you need to be getting tokens from response.data rather than in headers.

```javascript
Vue.http.interceptors.push({

    request: function(request) {

        const headers = request.headers;

        if (!headers.hasOwnProperty('Authorization')) {
            headers['Authorization'] = 'TOKEN';
        }

        // Return the request.
        return request;
    }
});
```

**Comment by aios** [comment]
You do not understand. My Vue app doesnt first step of update jwt. It doesnt make request for that. 
I have backend on laravel. And have middleware jwt.refresh. That is automatic refresh token when it invalid - and set header Authorization to response. With response i want get it Auth Token with vue-resource and set to headers on vue app.

**Comment by nblackburn** [comment]
Which you can do by combining my previous comments.

- Get the response header using the response interceptor.
- Store the token.
- Inject the token in future requests with the request interceptor OR with `Vue.http.headers.common['Authorization'] = 'TOKEN'`.

**Comment by aios** [comment]
So i make proof. Hold on 15 minutes.

**Comment by mlanin** [comment]
I have exactly the same problem. In response my api sends me these headers:
```
Access-Control-Allow-Origin:http://localhost:8080
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2FuZ2VsaWEuZGV2XC9wcm9qZWN0cyIsImlhdCI6MTQ1ODY1MzA4NiwiZXhwIjoxNDU4NjUzMTQ2LCJuYmYiOjE0NTg2NTMwODYsImp0aSI6ImE5NTAxNGRlYmM4N2YyZGM1YzJkNmI0YzgxNDEyYTRlIn0.rmy4i0ze5xTLRv4AjCGhAUbDiQfDlMZj7vaNAjFsees
Cache-Control:no-cache
Connection:keep-alive
Content-Type:application/json
Date:Tue, 22 Mar 2016 13:24:46 GMT
Server:nginx/1.9.11
Transfer-Encoding:chunked
Vary:Origin
```

But my response interceptor shows me this:
```
response (response) {
    console.log(response.headers(), response.headers('authorization'))
}
```
```
Object {content-type: "application/json", cache-control: "no-cache", "": ""}
undefined
```

**Comment by mlanin** [comment]
As far as I can see, problem is in [xhr.getAllResponseHeaders()](https://github.com/vuejs/vue-resource/blob/master/src/http/client/xhr.js#L24) function. It returns only these two headers. Strange...

**Comment by mlanin** [comment]
Figured out. I'm using cors requests with `Access-Control-Allow-Headers` header, but completely forgot about `Access-Control-Expose-Headers`. 

@aios I think you have the same issue. Just add this header on our backend side and add Authorization header in it's list.

**Comment by aios** [comment]
@mlanin Thanks!
!Solved!

**Comment by lucifercha** [comment]
@aios @mlanin  thanks ，it solved my problem
