### ISSUE TITLE
Track "state" of http request.

### ISSUE THREAD

**Issue by websanova** [vuejs/vue-resource#245]
Often elements in a page will show/hide based on the state of the http request.

~~~
this.registerState = 'sending';

this.$http.post('/auth/register, {}, function () {
    this.registerState = 'sent';
}, function () {
    this.registerstate = 'error';
});
~~~

This can get extremely redundant. It would be nice if there was a parameter that could be set for the request and the contexts data would automatically get updated.

~~~
this.$http.post('/auth/register, {}, function () {
}, {
    state: 'registerState'
});
~~~

Then in our view we just have access to `registerState` and don't need to constantly write up the logic.

**Comment by steffans** [comment]
Try to use an interceptor for state callback, see https://github.com/vuejs/vue-resource/blob/master/docs/http.md#interceptors

**Comment by websanova** [comment]
Yes, but how can I track a specific request? What if I have two buttons on my page and each perform a different function? For instance an "update" and "delete" which buttons hide when they are clicked. How would I differentiate this on the fly without having to sniff some url in an interceptor? (what if they url changes)

Also I need to be able to track the change in the current context. If there is a way to accomplish this with interceptors it would be great. But I have not found a method to accomplish it.

**Comment by nblackburn** [comment]
```javascript
Vue.http.get('https://example.com/api/v1/authenticate', {username: 'username', password: 'password'}, {
    xhr: {
        onprogress: function(event) {
          console.log(event);
        }
    }
});
```

You could do this via the third argument on a request and attaching a callback to the xhr object.

**Comment by websanova** [comment]
@nblackburn I see, but that doesn't seem to give all the states, let alone any syntactical sugaring. I know it's very easy to do currently. But having to manually type out all these state changes is getting redundant.

By the way, it's not a question, I'm proposing a new feature.

Consider:

```
export default {
    data() {
          return {
              registerState: 'init'
          };
    },
    methods: {
        this.registerState = 'sending';

        this.$http.post('/auth/register, {}, function () {
            this.registerState = 'sent';
        }, function () {
             this.registerstate = 'error';
       });
    }
}
```

Versus:

```
export default {
    data() {
          return {};
    },
    methods: {
        this.$http.post('/auth/register, {}, function () {

        },{
             track: 'registerState'
        });
    }
}
```

Or

```
export default {
    data() {
          return {};
    },
    methods: {
        this.$http.track(['registerState']).post('/auth/register, {}, function () {

        });
    }
}
```

The default states being `init`, `sending`, `sent`, `error`.

**Comment by nblackburn** [comment]
I know it's not a question, i was simply stating it was possible at present (_which is sometimes grounds for rejection_) even though i prefer your proposal. I have updated my example to cover all states rather than progress.
