### ISSUE TITLE
this.$http.post 不能正常使用 服务端获取不到参数

### ISSUE THREAD

**Issue by hxudong** [vuejs/vue-resource#246]
this.$http.post 不能正常使用 服务端获取不到参数

**Comment by kazupon** [comment]
Hello !!
Can you use the english please ?
Sorry, The maintainer cannot understand chinese. :crying_cat_face:

**Comment by ChacesXia** [comment]
I can't get data from server. the response is request data.
`{
    "request": {
        "method": "POST",
        "data": "{\"username\":\"113\",\"password\":\"xxxxx\"}",
        "params": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Origin": "http://121.249.216.217",
            "x_csrftoken": "OVZMMs485QDFqY2Ge7geCAKz5W9bIw7D",
            "crossOrigin": false
        },
        "xhr": null,
        "upload": null,
        "jsonp": "callback",
        "beforeSend": null,
        "crossOrigin": true,
        "emulateHTTP": false,
        "emulateJSON": false,
        "timeout": 0,
        "url": "http://121.249.216.217/account/login/"
    },
    "data": "",
    "status": 0,
    "statusText": "",
    "headers": "",
    "ok": false
}
`
this is my response data
