### ISSUE TITLE
Docs explaining reason for existence?

### ISSUE THREAD

**Issue by taoeffect** [vuejs/vue-resource#247]
I've searched through the existing documentation and issues but it's still not clear to me why this was created when things like jQuery, [superagent](https://github.com/visionmedia/superagent), and a variety of other options have been around and are battle tested for doing this exact same thing?

What are the advantages of `vue-resource`? What hole does it fill that things like `superagent` don't?

Would be great to see this explained in the README.md.

**Comment by smolinari** [comment]
I'd say, there is no particular reason. [As the docs mention](http://vuejs.org/guide/application.html#Communication-with-Server)....

>Communication with Server

>All Vue instances can have their raw $data directly serialized with JSON.stringify() with no additional effort. The community has contributed the vue-resource plugin, which provides an easy way to work with RESTful APIs. You can also use any Ajax library you like, e.g. $.ajax or SuperAgent. Vue.js also plays nicely with no-backend services such as Firebase and Parse.

Scott

**Comment by YerkoPalma** [comment]
Is simple made to be use with Vue, what other reason you need?

**Comment by taoeffect** [comment]
Hmm, well my only concern is if the maintenance of this detracts from other important Vue tools/plugins/components (I hope not).

Here's one advantage over jQuery: if all you need is AJAX then this is *much* smaller to include in your app bundle. However, superagent (surprisingly) turns out to have an even smaller line count, and that's with comments for every single method (so minified it's probably much less, yet seems to be just as if not more featureful).

**Comment by ralphking** [comment]
https://github.com/mzabriskie/axios is another good option - it's promise based like vue-resource/jquery, which superagent is not.

**Comment by taoeffect** [comment]
Cool, thanks for the link @ralphking! Thankfully it's not too difficult [to promisifiy superagent](https://github.com/visionmedia/superagent/issues/957).
