### ISSUE TITLE
Can't use http service globally

### ISSUE THREAD

**Issue by Dealerpriest** [vuejs/vue-resource#249]
I'm trying to use the http service globally.
`Vue.http.get('/json/logs'); `
Chrome devtools throws:
> Uncaught TypeError: Cannot read property '$vm' of undefined

Note that using
`
this.$http.get(...);
`
works fine. Also that the row below that sets the header works fine too.

```
Vue.use(require('./vendor/vue-resource'));

//Make sure we send along a token in the ajax requests
Vue.http.headers.common['X-CSRF-TOKEN'] = document.querySelector('#token').getAttribute('value');
Vue.http.get('/json/logs');  //This row makes the console throw the error.
```

**Comment by steffans** [comment]
Strict mode issue, is fixed in v0.7.3
