### ISSUE TITLE
Default Actions: Put method?

### ISSUE THREAD

**Issue by cage1016** [vuejs/vue-resource#25]
```javascript
// src/resource.js line 102
Resource.actions = {
        get: {method: 'get'},
        save: {method: 'post'},
        query: {method: 'get'},
        remove: {method: 'delete'},
        delete: {method: 'delete'}        
    };
```
Thanks for releasing `vue-resource` library. It's more convenient to call RESTful APIs. But, why default actions don'ts have `update: {method: 'put'}` method? (I add it by myself now) 

Thanks.

**Comment by Fauxide** [comment]
#23 PR :+1:

**Comment by cage1016** [comment]
@Fauxide Thanks. I saw 3a58c41 has been add. This issue can close. Thanks :-)
