### ISSUE TITLE
this.$http.post not works, it turn into get method.

### ISSUE THREAD

**Issue by VinceXie** [vuejs/vue-resource#251]
i used this.$http({method: 'POST'}) to fix. but i hope "this.$http.post" can be used

**Comment by indigoram89** [comment]
I have the same problem

**Comment by indigoram89** [comment]
I solved the problem for myself
i change root paramener:
from Vue.http.options.root = '/ajax'
to Vue.http.options.root = '/en/ajax'

**Comment by ykadosh** [comment]
This question was answerd here: [https://github.com/vuejs/vue-resource/issues/15](https://github.com/vuejs/vue-resource/issues/15)
> All post data is send as application/json by default, if you want to send as form-data can enable this option

For example:
```javascript
this.$http.post('http://example.com', data, {emulateJSON:true}).then(function(res){
    // Do something with the response
});
```

**Comment by HardlyMirage** [comment]
Why was this closed? I am getting the same issue, and I don't see a proper solution. If I use `this.$http.post` I expect to see a POST request being sent out, not a GET request.

**Comment by LinusBorg** [comment]
* The OP did not provide a reproduction
* Someone provided an answer.
* The OP did not react after an answer was provided.

Why should we leave the issue open?

If you see this problem, please provide a reproduction.

**Comment by HardlyMirage** [comment]
Fair enough! I notice this only happens on urls without FQDNs and without http/https scheme

http://jsfiddle.net/vjvMp/568/

http://i.imgur.com/DahzRUw.jpg

**Comment by LinusBorg** [comment]
Thanks for this! We will look it!

**Comment by radiosource** [comment]
I have the same problem:
this.$http.post('/api/autos', this.formatFormData()) - send GET request

The problem was solved by adding / to the end of request url
this.$http.post('/api/autos/', this.formatFormData()) - send POST request
