### ISSUE TITLE
Client side cache

### ISSUE THREAD

**Issue by xrado** [vuejs/vue-resource#252]
Any suggestion how hook cache mechanism inside request/response call? Interceptor looks like good place, but currently you cant trigger cached response from request hook, only cancel is available.

**Comment by xrado** [comment]
Ok I figure it out
```
  Vue.http.interceptors.push({
    request: function (req) {
      if(req.method.toLowerCase() == 'get') {
        var found = cache.get(req.url);
        if(found) {
          req.client = function(){
            return found;
          }
        }
      }
      return req;
    }
  });
```
ofcourse you need to set cache in response interceptor first
hope it helps to someone

**Comment by javisperez** [comment]
hey man, nice solution, thx, but what is the "client" property you're creating? i want to implement this but i don't know how to return the data from the request itself. i've tried return the request but is not working.

**Comment by xrado** [comment]
that's how is implemented in the source, ...req.client gets executed, I just set it as func which returns response

this is complete solution for caching get responses
```
var cache = new Cache({expiration: 300});

Vue.http.interceptors.push({
  request: function (req) {
    if(req.fresh) cache.del(req.url);
    if(req.method.toLowerCase() == 'get') { // check
      var valid = cache.get(req.url);
      if(valid) {
        req.client = function(){
          return valid;
        }
      }
    }
    return req;
  },
  response: function (res) {
    if(res && res.status == 200 && res.request.method.toLowerCase() == 'get') {
      cache.set(res.request.url,res); // set
    }
    return res;
  }
});
```

**Comment by javisperez** [comment]
Oh great thx, is just that seems like that interceptor syntax have changed so i'm kinda confused about the req.client part, but if that gets executed internally, i'll try to change it to the new syntax and if it works i'll post it here in case you need it.

Thank you ! :)

**Comment by xrado** [comment]
yes it look like internals of interceptors have changed, it look simpler now just modify and use next

**Comment by javisperez** [comment]
Hey man, thanks for your help, this is the final code, its working now, thank you a lot, didnt know about the client property, was just what i needed 👍 

`Vue.http.interceptors.push((request, next) => {
            if (request.method.toLowerCase() === 'get') {
                let _cache = Cache.get(request.url);

                if (_cache) {
                    request.client = function () {
                        return _cache;
                    };
                }
            }

            next((response) => {
                if (response.status === 200 && response.request.method.toLowerCase() === 'get') {
                    Cache.set(response.request.url, response);
                }
            });
        });`

**Comment by lbineau** [comment]
I get the following error because request is a Promise.
```javascript
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
```
Is it still working for you ?

**Comment by javisperez** [comment]
@lbineau weird i use promises too but is working great on me. What does that console.log(request) is displaying? i mean, what are you getting as request?

**Comment by lbineau** [comment]
```javascript
function Promise$1(executor, context) {

    if (executor instanceof PromiseObj) {
        this.promise = executor;
    } else {
        this.promise = new PromiseObj(executor.bind(context));
    }
...
```

**Comment by airtonix** [comment]
Meh, Because you want your downstream response handlers to continue using Resource.response objects, your caching interceptor actually needs to look like this:

```es6
let session = window.sessionStorage,
    log = console && console.log || function(){};

Vue.http.interceptors.push(function (request, next) {
	if (request.method.toLowerCase() === 'get') {
		var cache = session.get(`CACHE_${request.url}`);

		if (cache) {
			log('cache hit', request.url);
			next(request.respondWith(cache, {status: 200, statusText: 'Ok'}));
		} else {
			log('cache miss', request.url);
		}
	}


	next( function (response) {
		if (response.status === 200 && request.method.toLowerCase() === 'get') {
			log('cache save', request.url);
			session.set(`CACHE_${request.url}`, response.body);
		}

		setTimeout(request.respondWith(response), env.IS_DEV ? 5000 : 0);
	});
});
```

**Comment by Rebolon** [comment]
@airtonix i tried your solution but in fact even if the response is well stored in sessionStorage, i can see the HTTP call.
So the interceptors doesn't prevent the HTTP call, it just stores data

**Comment by javisperez** [comment]
@Rebolon I does prevent it, I've been using this solution since like July 2016 and is working so good I've never even touched it again :P

**Comment by Rebolon** [comment]
thx, so i don't do the call to next function inside my promise (using PouchDB for the cache system)

**Comment by l2aelba** [comment]
@airtonix Thanks for this. But something on the current version, this not return cache (localstorage 
 / localstorage) anymore.
