### ISSUE TITLE
Can't update data in PUT method

### ISSUE THREAD

**Issue by SimGyun** [vuejs/vue-resource#254]
I cant update data in put method, codes like:
putDate = {
    name:"haha",
    age:"22"
}
 this.$http.put(url,putDate).then()
WHY WHY WHY…

**Comment by jasontll** [comment]
I think you need to send json object. What response did you get on your server side?

**Comment by Nandiin** [comment]
I'm facing similar problem, and I haven't solved it yet. But somehow I might have found the point: 
`jQuery.ajax({method: 'PUT', data: jsonObj, url: 'somewhere.com'});` sends `jsonObj` as FormData while `Vue.http.put(url, jsonObj)` sends `jsonObj` as playload, which results a empty `$_POST` at server side.

**Comment by skyrpex** [comment]
When using PUT, data is sent within the request payload. If you're using PHP, you can do the following:

```php
$request = file_get_contents('php://input'); // This will be a string (possibly JSON). Use json_decode(...).
```

If you're using Symfony Requests:

```php
$request = Request::createFromGlobals()->getContent(); // This is a string too.
```
