### ISSUE TITLE
post method automatically changed to options ？

### ISSUE THREAD

**Issue by Yeahax** [vuejs/vue-resource#260]
```js
  Vue.http.interceptors.push(function () {
      return {

          request: function (request) {
              var tokenVal = sessionStorage.getItem("token");
              if(tokenVal) {
                request.beforeSend = function() {
                  request.headers['token'] = tokenVal
                }
              }
              return request;    
          },

          response: function (response) {
              return response;
          }

      };
  });
```

![image](https://cloud.githubusercontent.com/assets/8794879/14662812/6c677f0e-06ec-11e6-9966-efc67338632c.png)

After the headers to add a token, post method previously used to automatically become options

![image](https://cloud.githubusercontent.com/assets/8794879/14662830/aa36bf98-06ec-11e6-9899-ad9d25d39449.png)

Why?

**Comment by Yeahax** [comment]
I have resolved！

**Comment by varHarrie** [comment]
I have same problem,  how to resolve the issue?

**Comment by NicolasParada** [comment]
Maybe Cors btw?

**Comment by varHarrie** [comment]
@NicolasParada That's right. [#228](https://github.com/vuejs/vue-resource/issues/228)

**Comment by vad11** [comment]
Please solution of this problem!

**Comment by Yeahax** [comment]
please see  https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests

**Comment by stevenkitter** [comment]
please tell me how you solve this!

**Comment by jbiddulph** [comment]
I am having an issue with not being able to save data into a database  so I read about CORS and then installed it by following steps here: https://stackoverflow.com/questions/39429462/adding-access-control-allow-origin-header-response-in-laravel-5-3-passport

still not working?!
