### ISSUE TITLE
Loading Bar / Interceptor triggers on non Ajax Requests

### ISSUE THREAD

**Issue by mstaack** [vuejs/vue-resource#261]
I have the issue that the loading modal is shown even! for normal (non ajax) requests.

Unfortunately i not yet using components and vueify/browserfy in my laravel application:

```

Vue.http.interceptors.push({
    request (request) {
        $('#ajax-loader').modal('show');
        return request
    },

    response (response) {
        $('#ajax-loader').modal('hide');
        return response
    }
});

new Vue({

    el: '#app',


....
```

How should this be fixed?  WIll it be gone if i switch to components etc?

**Comment by romandragan** [comment]
@mstaack, have you solved the issue?
