### ISSUE TITLE
transition.redirect() still carries query and params

### ISSUE THREAD

**Issue by aperetti** [vuejs/vue-resource#266]
This isn't breaking anything at the moment but when I do the following
``` javascript 
router.beforeEach(function (transition) {
  if (!loggedIn() && !transition.to.path.includes('/login')) {
    transition.redirect('/login')
  } else {
    transition.next()
  }
})
```
The redirect carries all of the params and query of the intended route information. Is there a way of dropping that data?

**Comment by nivv** [comment]
@aperetti I think you'll have better luck posting this in the `vue-router`-repo 🍭  

https://github.com/vuejs/vue-router
