### ISSUE TITLE
How can i send vue resource POST with multipart/form-data

### ISSUE THREAD

**Issue by adhatama** [vuejs/vue-resource#267]
I didn't find any documentations about that.

**Comment by libertyAlone** [comment]
try this:
```
this.$http.post('/api', data, {
   headers: {
       'Content-Type': 'multipart/form-data'
   }
})
```

**Comment by ruelluna** [comment]
I'm also finding solutions for this.. Is there any update?

**Comment by steffans** [comment]
This will send request data as `application/x-www-form-urlencoded` content type.

```js
this.$http.post('/api', data, {
   emulateJSON: true
})
```
 Or use [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData)

```js
var formData = new FormData();
formData.append('foo', 'bar');

this.$http.post('/api', formData)
```

**Comment by raphcadiz** [comment]
I can't make it work with PUT when using formdata, any idea why this is happening?

```
 var data = new FormData()
 data.set('actual_po_reference', this.actual_po_reference)
  this.$http.put('/client, data).then((response) => {
  // result
 })
```

**Comment by brianirish** [comment]
A caveat to @steffans response, `FormData` and it's `append` apparently [has poor browser support](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append), particularly on mobile browsers.

**Comment by jofftiquez** [comment]
Just a reminder, none of theses solutions will work if you do not setup the `cors`. It won't even be in the error response.

**Comment by raphcadiz** [comment]
For the record guys, about the comment I have above, I was using Laravel, I realized you should still use post request and pass data '_method' with a value 'put'
```
data.set('_method', 'put')
this.$http.put('/client', data).then((response) => {
  // result
})
```

**Comment by 19930805** [comment]
How can i send file arg with multipart/form-data

**Comment by 19930805** [comment]
and add files

**Comment by anil11432** [comment]
for posting data in form data you can easily do...
in the place of "local storage" you can pass any variable or data.
         this.$http.post('/api', { params: {code: 'hello'}, headers: {'X-Auth': localStorage.token}},{emulateJSON: true})
            .then((resposne) => {
                console.log(response);
            })
            .catch(err => console.log('Error'));
        }

**Comment by ardinusawan** [comment]
And if you want to upload file too, that trick can be found here:
https://forum.vuejs.org/t/submitting-file-inputs/4960/5

**Comment by jpcmf** [comment]
Finally found a solution, thank you!

**Comment by TheLaughingGod1986** [comment]
@jpcmf  well what was the solution please share.

**Comment by jpcmf** [comment]
@TheLaughingGod1986 well, the solution above :)
