### ISSUE TITLE
xhr.responseType

### ISSUE THREAD

**Issue by 644379413** [vuejs/vue-resource#268]
When I need responsetype to return to the blob data,
But I always get the text type.
I find you XHR always get responseText

**Comment by steffans** [comment]
I fixed this issue in my last commit 1e472bc223434f4006b5b02bb94ce00fa1ea85c9. The `xhr.response` property will be used as data.

**Comment by migueljteixeira** [comment]
This is not working correctly.
The data is converted to string before the blob object is constructed.
