### ISSUE TITLE
options.url.replace is not a function(…)

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue-resource#269]
I get this error (url.js:22):

```
Uncaught (in promise) TypeError: options.url.replace is not a function(…)
```

Situation not isolated yet..

**Comment by abotsi** [comment]
Could you explain why you close it? Is there an explanation for this issue ?

**Comment by steffans** [comment]
@abotsi Its an issue from an old version, the line `options.url.replace` is not in the source code anymore.

**Comment by abotsi** [comment]
@steffans Ok, my bad so. 
By the way, I'm having trouble migrate to 1.2.x. I think that may be related to a similar error that is thrown in my project (description here : http://stackoverflow.com/questions/40114926/typeerror-str-replace-is-not-a-function-strange-error-with-vue-js-ajax-call). 
Do you have a migration plan or something to ease the update?
