### ISSUE TITLE
Feature Request: Timeouts

### ISSUE THREAD

**Issue by JoshZA** [vuejs/vue-resource#27]
We should be able to set the timeout on promises/requests, and handle accordingly

**Comment by rleger** [comment]
+1

**Comment by sulfo** [comment]
I'm positiv for this feature too. +1

**Comment by gefangshuai** [comment]
+1 toooooo

**Comment by steffans** [comment]
It's implemented in the current develop branch, have a try.

**Comment by steffans** [comment]
Available in v0.5.0.

**Comment by sulfo** [comment]
Awesome @steffans!
