### ISSUE TITLE
PATCH params sent as payload

### ISSUE THREAD

**Issue by ghunti** [vuejs/vue-resource#273]
Hi.
I was trying to make a PATCH request to my endpoint `users{/id}`, but found out that the data in case of POST/PUT/PATCH is always send as the payload, and not replaced in the url.
My API endpoint expects the PATCH to be something like `/users/7` when I'm updating the data for user number 7.
I know the "problem" is in [resources.js](https://github.com/vuejs/vue-resource/blob/master/src/resource.js#L68) but I don't know if you consider this a problem or not.

Edit: This only happens when using the resource `this.$resource`. Using `this.$http` with method PATCH, works perfeclty

Thanks

**Comment by Nandiin** [comment]
Add this setting `Vue.http.options.emulateJSON = true`

**Comment by ghunti** [comment]
Hi @Nandiin 
Thanks for the reply, but after all the mistake was mine.
I was doing `resource.save({id: 1, item: 'a'})` instead of `resource.save({id: 1}, {item: 'a'})`

Sorry for the confusion
