### ISSUE TITLE
Synchronous requests using vue-resource

### ISSUE THREAD

**Issue by ikilledthecat** [vuejs/vue-resource#274]
Didn't see it in the docs nor did a google search throw up the answer.

My app needs to load data from multiple sources in a specific order. I would like to implement it using synchronous requests but i've been unable to perform synchronous requests using vue-resource.

Can someone guide me in the right direction here.

Thanks

**Comment by cyberbuff** [comment]
If you need data in specific order, you might use `broadcast` and `dispatch` to communicate with components and make requests accordingly. Some example code may help us understand the problem better.

**Comment by steffans** [comment]
Duplicate, see #179
