### ISSUE TITLE
Array containing Objects not sent as request

### ISSUE THREAD

**Issue by danielwaghorn** [vuejs/vue-resource#277]
When sending an array of objects as a request it arrives at the server as empty. I looked into this and it appears to be due to the payload never being set (when `emulateJSON` is true) as none of the conditions in `mime.js` are met.

An example of a request would be something like this:

```
[Object, Object, Object...]
```

Which would typically give a result as below when `JSON.stringify` is used to transform it.

```
[
    { ... },
    { ... },
    { ... },
    ...
]
```

My proposal would be to add an additional condition to the if statement at line 20 to check if the payload might instead be an array, that would still allow it to be converted to JSON and sent as the request rather than being empty.

I'm wondering what others think of this incase it's done in this way for a particular reason, and if not then I can send a PR.

**Comment by steffans** [comment]
If you want to send Objects don't use the `emulateJSON`option and make sure your decodes the request with `application/json` content type properly.
