### ISSUE TITLE
when I use 'jsonp',navigator console error 'Uncaught SyntaxError: Unexpected token :'

### ISSUE THREAD

**Issue by Cuixote** [vuejs/vue-resource#278]
Here is my code 
` this.$http.jsonp('http://news-at.zhihu.com/api/4/news/latest',{
        'jsonp': 'callback'
      }).then(function (res) {
        console.log(res)
      })`
Here is the error tip
![image](https://cloud.githubusercontent.com/assets/10526614/15532394/2747518a-2292-11e6-8730-9368c7c3b6ac.png)

**Comment by githubmann** [comment]
how to solve it

**Comment by wacoom** [comment]
i got the same problem

**Comment by githubmann** [comment]
@wacoom  i think you should understand principle of jsonp  https://www.zhihu.com/question/19966531

**Comment by gkatsanos** [comment]
Same problem. Please add an example in the documentation. Many tickets open for this.

**Comment by zeroone001** [comment]
i got the same problem

**Comment by edgardong** [comment]
solved?

**Comment by NeonRider** [comment]
Why is this issue closed while there are still people encountering the problem? I'm having the same error as well..

**Comment by StKostya** [comment]
already 2018, but the problem remained

**Comment by gkatsanos** [comment]
@StKostya don't use this plugin :) it's abandoned by its owner. 
it's much easier to use either window.fetch or Axios. https://alligator.io/vuejs/rest-api-axios/ 
https://github.com/github/fetch
