### ISSUE TITLE
why the default xhr is async?can i set it sync?

### ISSUE THREAD

**Issue by laizhenhai88** [vuejs/vue-resource#282]
why the default xhr is async?can i set it sync?
maybe an async option is better

**Comment by aviggngyv** [comment]
+1

**Comment by Jogiter** [comment]
+1

**Comment by Nandiin** [comment]
in `/src/http/client/xhr.js` it's hard-coded as `xhr.open(request.method, _.url(request), true);` and I don't know any alternative way to make a xhr request sync except for opening it with a `false` at 3rd argument.
So maybe you can't turn it to sync for now.

One can set properties to xhr by doing this: `Vue.http.get(url, data, params, { xhr: { something} })`, the `xhr` field in `options` argument will be merged into actual xhr object. But I don't know whether there is a way to make a xhr sync by setting its property.

**Comment by steffans** [comment]
Duplicate, see #179
