### ISSUE TITLE
[question] Browser compatibility and use as mixin feature

### ISSUE THREAD

**Issue by dariuszsikorski** [vuejs/vue-resource#284]
I don't see the browser compatibility table in documentation.
Will Vue-Resource work in the same browsers as Vue or has some specific browser limitations?

To be precise what i look for is IE9+ compatibility and Android 4+

Second thing:
Can Vue-Resource be used as a mixin for only specific component instead of extension of entire Vue object?

Simmilar library https://github.com/vuejs/vue-async-data offers functionality as a Mixin.

Regards

**Comment by LinusBorg** [comment]
It's a basic XMLHttpRequest client, so browser compatiblity should not be an issue.

Concerning the mixin question: No, that is currently not possible. MAy I ask what specific advantage do you see in providing this functionality as a mixin?

**Comment by steffans** [comment]
Yes, it's IE9+ and Android 4+ should as well. Why do you need a mixin? It's already available globally and on each instance, see https://github.com/vuejs/vue-resource/blob/master/docs/http.md#methods
