### ISSUE TITLE
when data is array vue-resource add's [] to the end of param

### ISSUE THREAD

**Issue by ZucchiniZe** [vuejs/vue-resource#289]
This causes issues with many things, in my case django forms, and it is not default behavior for forms, it is a php legacy behavior. Is there an option to toggle these or somewhere in the code where they are getting added so I can remove it?

edit: just read over #259 and found out that you can only use the URI templating with get requests, not post requests. Is there a way to use it with post requests?

**Comment by steffans** [comment]
Yes, it works also with post requests. You need to use the `params` option:
```js
Vue.http.post('/someUrl', [post data], {params:  {
    id: this.application.id,
    max: 50,
    category: this.selected_categories
}}).then(successCallback, errorCallback);
```

**Comment by savokiss** [comment]
What about the added `[]` to the end of array data?
I have 2 params and one of them is an array: `agentGids`, but when i send them with post method, the array automatically added `[]` to the end, form data as below:
```
userGid:e2f1a0a5160c4e96bba2889c4aa80e01
agentGids[]:7e6b0466f6a24a2db240320071b21383
agentGids[]:c9a09f190cc14ced9afb601bdcdb541a
```

How can i remove the `[]` ?

**Comment by vstorm** [comment]
@savokiss +1, same problem,have you solve it?

**Comment by savokiss** [comment]
@vstorm no, we finally send ids as string which seperated by comma.
Another opened issue #407

**Comment by phoenix1331** [comment]
I had a similar issue.

```
// agentGids = [1,2,3,4];

{id:vm.agentGids.toString()}
```

Worked for me

**Comment by Yuiffy** [comment]
same issue!
`        data: {
            rankListObj: {
                name: "",
                description: "",
                productionStartDate: "",
                productionEndDate: "",
                category: [],
                team: [],
                tag: []
            },`
`                this.$http.get(this.apiUrl, {'params': this.rankListObj})
and the url query will be:
`name=&description=&productionStartDate=&productionEndDate=&category%5B%5D=1&category%5B%5D=2&category%5B%5D=3&category%5B%5D=4&category%5B%5D=5&category%5B%5D=6&team%5B%5D=2&team%5B%5D=1&tag%5B%5D=1&tag%5B%5D=29
it means:
```
name:
description:
productionStartDate:
productionEndDate:
category[]:1
category[]:2
category[]:3
category[]:4
category[]:5
category[]:6
team[]:2
team[]:1
tag[]:1
tag[]:29
```
WHY IT ADD "[]" ??

**Comment by seifsay3d** [comment]
@Yuiffy have you been able to find out why it adds []?

**Comment by zili2000** [comment]
params also have error；
when the value is {filter:{updated_at:[]}}，updated_at params lose;

But there is a way to solve this question:
```
before: request => {
      if (request.params) {
        request.url += '?' + Qs.stringify(request.params, {
          arrayFormat: 'brackets'
        })
        request.params = null
      }
    }
```

**Comment by rp-21** [comment]
i have been defining custom resources for the urls 
./resourcessss.js
something = Vue.resource( '/mt/quotes/list{/store_ucode}/{?q*}',  ),

./htapi.js
resourcessss.something.get ({ store_ucode: args.store_ucode, q: args.query_params })

If you checkout https://medialize.github.io/URI.js/uri-template.html
you can see the syntax of how to pass a single object for query parameters instead of mentioning each qury param one by one as in the discussions above.

In case normal this.$http use the params option it works.

**Comment by andreygalassi** [comment]
meybe
```
Vue.http.interceptors.push(function(request, next) {
	if (request.method === "GET") {
		let data = Object.assign({}, request.params);
		for (let i = 0, key; key = Object.keys(data)[i]; i++)
			if (Array.isArray(data[key])) 
				request.url+='{?'+key+'*}'
	}
	next();
})
```
