### ISSUE TITLE
How do I handle a request when is loading up?

### ISSUE THREAD

**Issue by socieboy** [vuejs/vue-resource#29]
I would liek to show a image loading up during the process of the http request to the server.
How do i do that on this?

```
this.$http.get('install/, function (data, status, request) {
    console.log(status)   
}).error(function (data, status, request) {
})
```

**Comment by Sherryar** [comment]
I'm also interested in this.  I'm used to using jQuery promises a lot which helped.   But there's no examples here except .error and .success...

I remember in Ractive.js I did a 'Loading...' until the request returned back data.  But not sure how to do it here.

I'm currently loading a list of tasks (trying to implement pagination as well, but a bit complicated using it with Laravel and Vue.js - any examples?), and whilst loading, I need a spinner or some text to let the user know that the tasks are being populated.

Thanks.

**Comment by socieboy** [comment]
I make this but I'm not sure is the best wat!

```
this.isLoading = true;

    this.$http.get('my/route/' ,function () {
        this.isLoading = false;
    });
```
Template
```
<div v-if="isLoading>
    <img src="imagen.png">
</div>
```

**Comment by steffans** [comment]
You can define a `onprogress` callback on the `XMLHttpRequest`:

```js
this.$http.get('my/route/', function (data) {
      // success code ...
}, {xhr: {
     onprogress: function(event) {
        // progress code ...
     }
   }
});
```
