### ISSUE TITLE
What is the point of this.$promise?

### ISSUE THREAD

**Issue by mrcsmcln** [vuejs/vue-resource#290]
If I want to call, for example, `.all()` on a promise object, I need to use `Vue.Promise.all()`, not `this.$promise.all()`, because, as Chrome tells me, `this.$promise.all` is not a function. So, what's the point of having `this.$promise`? I feel that `this.$promise` seems more Vue-like than `Vue.Promise`.

What am I missing here?

**Comment by steffans** [comment]
It acts as a factory function to create a new Promise Object which is automatically bound to the current Vue instance. You could write `new Vue.Promise(function() ..., this)` to get the same result.
