### ISSUE TITLE
Accept Headers

### ISSUE THREAD

**Issue by ruiposse** [vuejs/vue-resource#291]
Hi all,

In order to change the accept header of a request, I was excepting that I could do something in the lines of:
```
Vue.http.get(`/my/awesome/endpoint`, null, {
  headers: {
    accept: ''text/csv''
  }
})
```

But unfortunately that doesn't work, because the provided accept header string gets concatenated with `Vue.http.headers.common`. So as a workaround I have to do something ugly like this:

```
const tmp = Vue.http.headers.common
Vue.http.headers.common = {}

Vue.http.get(`/my/awesome/endpoint`, null, {
  headers: {
    accept: ''text/csv''
  }
}).finally(() => {
  Vue.http.headers.common = tmp
})
```

Is this the intended behaviour? Could this be somehow improved?

Thanks!

**Comment by steffans** [comment]
The header are always merged with the defaults, but the keys are case-sensitive. Try `accept` with uppercase `A`

```js
Vue.http.get(`/my/awesome/endpoint`, null, {
  headers: {
    Accept: "text/csv"
  }
})
```

**Comment by ruiposse** [comment]
> The header are always merged with the defaults

The defaults are [here](https://github.com/vuejs/vue-resource/blob/master/src/http/index.js#L73): `{'Accept': 'application/json, text/plain, */*'}`, which means they will get merged with whatever header I pass as an option.

In the example I provided, it becomes `'Accept': 'text/csv, application/json, text/plain, */*'`.
But more often than not, one would expect it to become `'Accept': 'text/csv'`.

Wouldn't it be better to replace whatever header is passed, instead of merging? And obviously, if no header is passed, then the default would be used.

**Comment by steffans** [comment]
Yes, the default header will be replaced when passing `headers: {}`, this happens the objects are merged. Try the code i posted before. Works for me.

**Comment by ruiposse** [comment]
Ok got it ! Thanks @steffans 👍
