### ISSUE TITLE
ES6 won't be comiled

### ISSUE THREAD

**Issue by CinKon** [vuejs/vue-resource#293]
With the new Version > 0.7.0, vue-resource uses ES6-Imports for "Promise". 
Vue-Webpack doesn't compile the node_modules-Folder, so I get the Error "Unexpected Token 'import'" in my app.js.

**Comment by steffans** [comment]
With Webpack make sure to include `dist/vue-resource.common.js`, which is ES5. All files in `src` use ES6.
