### ISSUE TITLE
Trying to call Vue.http.post gives an error from vue-resource Client

### ISSUE THREAD

**Issue by RPDeshaies** [vuejs/vue-resource#298]
I'm trying to call an api using the following code

```
import Vue from 'vue';
export default {
  ready : () => {
   Vue.http.post('/my-api', {}).then((response) => {
       //success
    }, (response) => {
      //error
    });
  }
};
```
I recieve the following error inside my chrome dev console
```
TypeError: reqHandlers.pop(...).call is not a function(…)
error @ vue-resource.common.js?2f13:311
(anonymous function) @ vue-resource.common.js?2f13:1152
```

![](https://i.imgur.com/26jINOe.png)

I tried using this.$http.post but I always the an error telling me that `this` is `undefined`

version : ^0.8.0

**Comment by danielschmitz** [comment]
try this:

```
export default {
  ready() {
   this.$http.post('/my-api', {}).then((response) => {
       //success
    }, (response) => {
      //error
    });
  }
};
```

**Comment by RPDeshaies** [comment]
Ok, using this syntax, I can access `this` but I still have the same error
`TypeError: reqHandlers.pop(...).call is not a function(…)`

**Comment by steffans** [comment]
In v0.8.0 the interceptor syntax changed, make sure to update your interceptor code. See https://github.com/vuejs/vue-resource/blob/master/docs/http.md#interceptors

**Comment by RPDeshaies** [comment]
Ok ! I'll try that. 

Also, on a different matter, whats the best practive on how to use vue-ressource inside an **vuex's action** ?

**Comment by czciou** [comment]
issue +1

**Comment by czciou** [comment]
@steffans  is right.when change your interceptor code.the error disappear
