### ISSUE TITLE
IE9 cant get response data

### ISSUE THREAD

**Issue by facesea** [vuejs/vue-resource#299]
i read code, vue-resource use `XDomainRequest` when brower is ie9, but ie9 cant get any data in response, so, i change code `var supportCors = 'withCredentials' in new XMLHttpRequest();` to `var supportCors = true;`, then it work!!!

**Comment by baiyts** [comment]
+1

**Comment by pkeros** [comment]
+1

**Comment by soundtina** [comment]
I also have this problem ! **+1**

**Comment by tolerious** [comment]
do you mean you change the source vue-resource  source code?

**Comment by hellovue2017** [comment]
我也遇到同样的问题，在IE9上请问怎么解决？

**Comment by soundtina** [comment]
@hellove2017 别用这个库了，建议使用axios
