### ISSUE TITLE
Aborting a request midflight

### ISSUE THREAD

**Issue by JosephSilber** [vuejs/vue-resource#3]
Any plans to support aborting a request midflight?

---

jQuery just uses the underlying `XMLHttpRequest`'s `abort` method:

```js
var jqxhr = $.get('api/foo');

jqhxr.abort();
```

Angular uses this weird `timeout` promise dance:

```js
var aborter = $q.defer();

$http({
	method: 'get',
	url: 'api/foo',
	timeout: aborter.promise,
});

// This aborts the request:
aborter.resolve();
```

---

Aborting a request midflight is very important in countless scenarios. For example in a typeahead, where - in addition to debouncing/throttling the actual request - you'd want to cancel the existing request when the user starts typing again.

**Comment by steffans** [comment]
Yes, it's possible to add a abort() function to the promise object, which the HTTP request function returns. This will allow a syntax similar to jQuery.

**Comment by JosephSilber** [comment]
@steffans that's great news! Always prefer the pragmatic approach over some ideal dream of architectural purity :smile:

**Comment by JosephSilber** [comment]
[The way it currently works](https://github.com/vuejs/vue-resource/blob/master/src/http.js#L34) will have to be refactored a bit.

We now don't have access to the `xhr` outside the resolver function. If we are to augment the promise with an `abort` function, we'll need access to the underlying `xhr` object.

**Comment by sahibalejandro** [comment]
Any examples about how to use this feature? I'm trying to use it but get `abort is not a function` error.

**Comment by steffans** [comment]
You could use the `beforeSend` callback to access the request object and a add your code to abort the current request.

```js
this.$http.post('url', function (data) {}, {beforeSend: function(xhr) {
    // use XMLHttpRequest and add xhr.abort callback
}});
```

**Comment by sahibalejandro** [comment]
Nice, it works! I ended with something like this:

````js
beforeSend(xhr) {
    if (globalXhr) {
        globalXhr.abort();
    }

    globalXhr = xhr;
}
````

**Comment by WilliamDu1981** [comment]
@sahibalejandro I try this.The beforeSend's arguments is a request object,But it's property xhr is null

**Comment by BrockReece** [comment]
@WilliamDu1981 
I've just had the same issue and looked at the request object, it has a cancel function which aborts the request behind the scenes for you. The code below is working for me
```js
beforeSend(xhr) {
    if (this.lastRequest) {
        this.lastRequest.cancel()
    }
    this.lastRequest = xhr
},
```

**Comment by WilliamDu1981** [comment]
@BrockReece I tried your code:
```
this.$http.get('/users',{},{
        beforeSend(xhr){
          debugger;
          if (this.lastRequest) {
            this.lastRequest.cancel()
          }
          this.lastRequest = xhr

        }
      });
```
but throw an error below:

```
App.vue?0940:60 Uncaught (in promise) TypeError: this.lastRequest.cancel is not a function(…)
```

the xhr object has not a method named cancel

**Comment by BrockReece** [comment]
I don't know sorry.
The source shows the object should have a cancel method

https://github.com/vuejs/vue-resource/blob/a27faffb8dbf7a7d7a7aaa8e3792e93f48a8a8c5/src/http/client/xhr.js#L14

Can you console.log the lastRequest obj?

**Comment by WilliamDu1981** [comment]
@BrockReece I've watched expression and screenshots
![vue-resource](https://cloud.githubusercontent.com/assets/6104369/16290182/dcd0ce1c-392d-11e6-8ef9-1066a8aaec6e.jpg)

**Comment by BrockReece** [comment]
@WilliamDu1981 This is my code that works, what version of vue resource are you using?
```js
this.$http.post(this.url, data, {
    beforeSend(xhr) {
        if (this.lastRequest) {
            this.lastRequest.cancel()
        }
        this.lastRequest = xhr
    },
}).then(response => {
...
}
```

**Comment by WilliamDu1981** [comment]
@BrockReece I install it via npm,It should be the newest version。
I find the code in xhr.js:
```js
var xhr = new XMLHttpRequest(), response = {request: request}, handler;
	
        request.cancel = () => {
            xhr.abort();
        };
```
I add breakpoints in this code and beforeSend,I found it execution after beforeSend,so when the beforeSend execution,the cancel method is not defined yet;
