### ISSUE TITLE
Wildcard in request object not replaced with value

### ISSUE THREAD

**Issue by b12k** [vuejs/vue-resource#300]
Hello!
I have a resource in a component:
```javascript
_resource = this.$resource(`channels/${this.$route.params.id}{/subResource}`);
_resource.get({subResource: 'memberships'}).then(res => this.memberships = res.data.data);
```

When I observe object structure in ChromeDevTools I see the following => http://prntscr.com/bjzqqp
(I grab it in interceptor).

Url parameter is expected to be ```channels/20/memberships```

Thank you in advance.

**Comment by steffans** [comment]
Please check this issue here, #302
