### ISSUE TITLE
request.url with parse params on interceptors

### ISSUE THREAD

**Issue by javisperez** [vuejs/vue-resource#302]
Hello,

I have an interceptor in which i need to use the request.url value but when i have an url with parameters, i dont get the parsed url if a request is made, i just get the url with the parameter, for example:

```
let resource = Vue.resource('/api/content{/id}');
```
if i make a get:
```
resource.get({id: 123});
```
in the interceptor, the request.url value is 
```
'/api/content{/id}'
```
instead of 
```
'/api/content/123'
```

Any idea how to get the parsed final url? Thank you

Edit: the request.params object does have 
```
id: 123
``` 
and that's great but i need the full url and i dont want to make my own parser with regular expression or something, any idea?

**Comment by javisperez** [comment]
So far i figured that i can do this:
```
Vue.url(request.url, request.params)
```

and seems to be working, i don't know if that's the right way to do it, but its working. Is that right?

**Comment by steffans** [comment]
Yes, this how the url is resolved before it is send. Im working on v0.9 in the develop branch, in this new version i added a function `request.getUrl()` wich always returns the parsed url.
