### ISSUE TITLE
Problem with Vue.http.options.emulateJSON 

### ISSUE THREAD

**Issue by hilmanrdn** [vuejs/vue-resource#304]
The Vue.http.options.emulateJSON  on version 0.9 , can't read data $_POST
* i load the data from cdn, when i use 0.8 it works, but 0.9 not

**Comment by steffans** [comment]
My test works, here is a jsfiddle: https://jsfiddle.net/x2ah10yb/

**Comment by hilmanrdn** [comment]
i believe the problem when you try send out a data.. so try instead html : .. || data: { id: id }
thanks for the response

**Comment by steffans** [comment]
With v0.9 the request `data` option was renamed to `body`. If you pass the data in the options you have to use `body: { id: id }`

**Comment by hilmanrdn** [comment]
thanks steffans, sorry didn't read the doc carefully

**Comment by awebdesigner** [comment]
Example in jsfiddle above by @steffans works. Is it necessary in VueJs 2+. Wanna be sure.
Thanks @steffans
