### ISSUE TITLE
arr.slice().sort is not a function v0.9.0

### ISSUE THREAD

**Issue by nathanaelphilip** [vuejs/vue-resource#307]
Hi hi!

I’m getting this error: `Uncaught TypeError: arr.slice(...).sort is not a function`

trace:

```
orderBy	@	vue.js?ver=1.0.26:9727
Vue._applyFilters	@	vue.js?ver=1.0.26:8812
Watcher.get	@	vue.js?ver=1.0.26:3192
Watcher.run	@	vue.js?ver=1.0.26:3318
runBatcherQueue	@	vue.js?ver=1.0.26:3075
flushBatcherQueue	@	vue.js?ver=1.0.26:3045
nextTickHandler	@	vue.js?ver=1.0.26:449
```

Using:

Vue.js: 1.0.26
Vuex: 0.8.2
VueResource: 0.9.0

Moving down to `0.8.0` removes the error

**Comment by IamSwap** [comment]
+1 Facing same issue but on https.

**Comment by steffans** [comment]
This trace does not relate to Vue.resource, only to the Vue library itself.
