### ISSUE TITLE
set cookie which with a specific path  

### ISSUE THREAD

**Issue by funkyLover** [vuejs/vue-resource#308]
I work a project with `vue-router`
the response from server get a set-cookie header 
` 'set-cookie': [ 'JSESSIONID=47BA62D1A1F9646BE03042C9D0D1479D; Path=/root/; HttpOnly' ]`
router configuration
```js
var router = new VueRouter({
  saveScrollPosition: true,
  history: true,
  hashbang: false,
  root: '/root'
})
```
how should I do to fit the server? make all requests take up that cookie in path `/root`

**Comment by steffans** [comment]
Try the https://github.com/vuejs/vue-router repo
