### ISSUE TITLE
Won't decode JSON

### ISSUE THREAD

**Issue by Jigsaw5279** [vuejs/vue-resource#314]
On my production server, vue-resource won't unwrap a json response, despite having the correct `Content-Type` headers.

The issue only appears in chrome and is reproducible:

![Production Server](http://puu.sh/pOSSj/eeca75d2cc.png)

On my Testserver, the very same line produces the following output (compare `data` attribute):

![Test Server](http://puu.sh/pOTcc/1124efaad4.png)

I tried removing the custom X- headers and other things, but I just can't get it to run properly..

**Comment by Jigsaw5279** [comment]
I think I've found the error. the body interceptor explicity looks for `Content-Type` in uppercase letters.

I'm using SPDY with my nginx server and it requires headers to be lowercase.
Therefor the content-type header is not found and thy body is not converted into an object.

**Comment by Jigsaw5279** [comment]
Yup.
Solved the Issue by using a custom interceptor:

```javascript
Vue.http.interceptors.unshift(function(request, next) {
    next(function(response) {
        if(typeof response.headers['content-type'] != 'undefined') {
            response.headers['Content-Type'] = response.headers['content-type'];
        }
    });
});
```

**Comment by hyiso** [comment]
got the same problem, thx for your solution👍

**Comment by citti** [comment]
just an FYI - outdated versions of PHP cause this issue as well. need to be >5.4 i believe.
