### ISSUE TITLE
res.blob() bug

### ISSUE THREAD

**Issue by luoye-fe** [vuejs/vue-resource#320]
When I want to use `res.blob()` to get an blob object, it's return an error blob ... 
[example in jsFiddle](https://jsfiddle.net/92c1kegx/)

Look at the source code, you is to use `new Blob([res.body])` to return an blob, but if not set `xhr.responseType = 'blob'`, it is not a binary stream ...

In fact, I think you can use the `fetch api`, of course, need to add polyfill, like [this(fetch polyfill)](https://github.com/github/fetch). 

:smiley:

**Comment by steffans** [comment]
Thanks, i will look into this bug.
