### ISSUE TITLE
最新版本0.93 跨域 配置 {xhr: {withCredentials: true}} 无法带 cookie

### ISSUE THREAD

**Issue by ickeep** [vuejs/vue-resource#323]
Vue.http.post('/user/login', this.form, {xhr: {withCredentials: true}})
无法带上cookie  
原 vue-resource v0.7.4 没问题！

**Comment by maniator** [comment]
What?

**Comment by lh8725473** [comment]
我也有同样的问题 被迫降低到vue-resource v0.7.4 没问题！

**Comment by steffans** [comment]
See  #327

**Comment by Rockergmail** [comment]
虽然我用0.9.3设置了credentials: true，但是不能传cookie，换成jquery的话就可以。你们有这种情况吗？详见：https://segmentfault.com/q/1010000005981906

**Comment by tinlee** [comment]
Vue.http.interceptors.push((request, next) => {
	request.credentials=true;

**Comment by bestsamcn** [comment]
楼上+1

**Comment by Mrwaite** [comment]
前端使用vue-resource 拦截器:
Vue.http.interceptors.push((request, next) => {
    request.credentials = true
    next()
})
后端设置res.header('Access-Control-Allow-Origin', 'XXXX');
注意设置了credentials = true,就不能设置'Access-Control-Allow-Origin', '*',会报错的.

**Comment by taurusser** [comment]
楼上+1

**Comment by Thinking80s** [comment]
Vue.http.interceptors.push((request, next) => {
request.credentials=true;

**Comment by Thinking80s** [comment]
http://www.ruanyifeng.com/blog/2016/04/cors.html

**Comment by kbqncf** [comment]
good job!
