### ISSUE TITLE
POST body as an Array not works

### ISSUE THREAD

**Issue by fritx** [vuejs/vue-resource#324]
In Devtools, Request Payload becomes `[object Object]`
Vue-resource version: 0.9.3

```js
// this works
const data = [{}, {}, {}]
const body = JSON.stringify(data)
return Vue.http({ url, method, body })

// doesn't work
const body = [{}, {}, {}]
return Vue.http({ url, method, body })
}
```

JSON.stringify is required, which is annoying.
However,  both work if POST body as Object.
Is anything to be improved?
Cheers!

**Comment by crabmusket** [comment]
I just ran into this as well. It seems like [this line](https://github.com/vuejs/vue-resource/blob/master/src/http/client/xhr.js#L47) is responsible for sending the body, but I can't find mention of being able to even send a plain object in

**Comment by akozenko** [comment]
I have the same problem with PUT.

small hanges in `./http/interceptor/body.js` fix it.

```javascript
    if (isPlainObject(request.body) || isArray(request.body)) {
        request.body = JSON.stringify(request.body);
    }
```


#388
