### ISSUE TITLE
How can I do something after every ajax request whether success or error?

### ISSUE THREAD

**Issue by ryanmortier** [vuejs/vue-resource#325]
When I was still using jQuery for all my ajax, I would do something like this:

```js
$( document ).ajaxComplete(function() {
    // do something
});
```

This doesn't work anymore now that I have all my ajax requests using Vue Resource. How would I accomplish the same thing using this package?

Thank you.

**Comment by andreldm** [comment]
I need to use [nprogress](https://github.com/rstacruz/nprogress/) and it would be great to intercept the end of ajax requests or use event handlers, i.e.:

```
$(document).on('vue-resource:start', function() { NProgress.start(); });
$(document).on('vue-resource:end', function() { NProgress.done();  });
```

**Comment by ryanmortier** [comment]
Same. Using interceptors I was able to do what I needed.

**Comment by lbchuan** [comment]
Vue.http.interceptors.push({
        request: function(request){
           // do something
            return request
        },
        response: function(response){
            // do something
            return response
        }
    });
