### ISSUE TITLE
xhr: {withCredentials: true} is not work on v.0.93  but work on v.0.7.4

### ISSUE THREAD

**Issue by lh8725473** [vuejs/vue-resource#327]
xhr: {withCredentials: true} is not work on v.0.93  but work on v0.7.4

**Comment by steffans** [comment]
The option has changed, now its just {credentials: true}

**Comment by Rockergmail** [comment]
@steffans 
Although i use the latest API to turn on the credentials option, it still can not transfer CORS cookie. 
Using JQ, I can transfer that. So it's not my CORS cookie setting problem.
If you can do that in v0.9.3?

**Comment by Rockergmail** [comment]
@steffans btw, I have reset the default header within the 'POST' method, avoiding using OPTION method.

**Comment by lh8725473** [comment]
@Rockergmail  you can use
Vue.http.options.xhr = {credentials: true} in global

**Comment by Rockergmail** [comment]
@lh8725473 when using v0.9.3 API, can you transfer the CORS cookies ?

**Comment by lh8725473** [comment]
@Rockergmail  yes

**Comment by youngerheart** [comment]
@lh8725473 there's only one setting in https://github.com/vuejs/vue-resource/blob/2f951df7261a5bd940438addf83b2a13de06c873/src/http/client/xhr.js#L39,
and, after trying I don't think Vue.http.options.xhr = {credentials: true} is useful.

**Comment by youngerheart** [comment]
wow, after use 
```
Vue.http.options.credentials = true;
```
It's works well!

**Comment by aios** [comment]
That option doesnt work on 0.9.3

```
var createCORSRequest = function(method, url) {
  var xhr = new XMLHttpRequest();
  if ("withCredentials" in xhr) {
    // Most browsers.
    xhr.open(method, url, true);
  } else if (typeof XDomainRequest != "undefined") {
    // IE8 & IE9
    xhr = new XDomainRequest();
    xhr.open(method, url);
  } else {
    // CORS not supported.
    xhr = null;
  }
  return xhr;
};

var url = 'CORS URL HERE';
var method = 'POST';
var xhr = createCORSRequest(method, url);

xhr.onload = function() {
  // Success code goes here.
};

xhr.onerror = function() {
  // Error code goes here.
};

xhr.withCredentials = true;
xhr.send();
```

that code working - instead of vue-resource
