### ISSUE TITLE
this.$http.get with parameter not working on 0.9.3

### ISSUE THREAD

**Issue by pchaow** [vuejs/vue-resource#330]
I have this code 
`
this.$http.get('/api/farm-owner', this.form).then(
                            function (response) {

                                this.farmOwnerPage = response.data;
                                this.farmOwners = this.farmOwnerPage.data;
                            },
                            function (error) {

                            }
                    );
`
version 0.7.4 : http://localhost:8000/api/farm-owner?keyword=123
but version 0.9.4 :  http://localhost:8000/api/farm-owner

the query string parameter was binding good in version 0.7.4
but in 0.9.4 it wasn't binding query string.

**Comment by LinusBorg** [comment]
[Release notes on 0.9.0](https://github.com/vuejs/vue-resource/releases/tag/0.9.0)

> * Changed arguments for `Http.get(url, [data], [options])` to `Http.get(url, [options])`

So this should probably now look like:

```js
this.$http.get('/api/farm-owner', {params: this.form}).then( )
```

**Comment by pchaow** [comment]
Thanks, That's working.
