### ISSUE TITLE
Syntax error in ajax response '=>'

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vue-resource#333]
On iPhone (Safari, Chrome) and on OSX Safari I get the following error in console:

> SyntaxError: Unexpected token '>'

Pointing to this line:

`this.$http.patch('/api/things/' + id, thing, { method: 'PATCH'}).then((response) => {`

**Comment by steffans** [comment]
The example uses ES6 syntax, https://babeljs.io/

**Comment by didamaran** [comment]
so we have to compile/translate any vue files that are using vue-resource with babeljs? there's no way around it?
I'm running in the same error with safari 9.1 (no problems with chrome or firefox, though)

**Comment by LinusBorg** [comment]
the **example** uses ES6 syntax (namely arrow functions), no one is forcing you to use it this way and ES6 is not required to use vue-resource.

Concerning the example, instead of this:

>.then((response) => { ..

simply do this:

> .then( function (response) { ..

**Comment by didamaran** [comment]
thanks LinusBorg, it works - kind of;
does it have any implications on how the returned data is handled?

my url returns an array, and with this:
this.$http.get(url).then((r) => {
	this.store = r.data;
});
this.store contains the returned array

but with this
this.$http.get(url).then( function(r) {
	this.store = r.data;
});
this.store remains empty, even though logging r.data to the console tells me, that url returned the same array?

**Comment by LinusBorg** [comment]
> does it have any implications on how the returned data is handled?

I thought no, but it turns out yes.

* No, the second example should work, because vue-resource binds the callback to `this`. At least it did last time I used it with a normal function callback. Seems it doesn't anymore.
* So yes, you have to func the function to the current scope:
```js
.then(function (response) {
 ...
}.bind(this))
```
.. or use a closure.
