### ISSUE TITLE
Delete not passing JSON.stringify Value

### ISSUE THREAD

**Issue by nacr-dev** [vuejs/vue-resource#334]
Hello, I'm pretty shore this was working.

Has something been changed?

that.$http.delete(
   '/dssds/'+that.record.number,
   JSON.stringify({id: that.record.id})
);

**Comment by nacr-dev** [comment]
@steffans can you help? I have checked and this is happening since my update to version 0.9.0 if I rollback to any other version this will work.

I have checked the request and it's still a post but all the parameters I put after url are ignored.

I really need help here.

Tks

**Comment by decademoon** [comment]
Have you tried

```
that.$http.delete('/dssds/' + that.record.number, {
  body: { id: that.record.id },
});
```

(stringify may or may not be necessary here). You should check the docs https://github.com/vuejs/vue-resource/blob/master/docs/http.md

**Comment by nacr-dev** [comment]
@decademoon tks dude, this resolves my problem.

But I dont get it, hmmm probably I have to read some more about this.

**Comment by decademoon** [comment]
The documentation page lists these shortcut methods:

- `get(url, [options])`
- `head(url, [options])`
- `delete(url, [options])`
- `jsonp(url, [options])`
- `post(url, [body], [options])`
- `put(url, [body], [options])`
- `patch(url, [body], [options])`

It's common for the POST, PUT and PATCH methods to have body data, so the second argument for those methods is the body. It's uncommon for DELETE requests to have a body, so if you want to specify the body for a DELETE request, you have to pass it via the `options` argument.

**Comment by steffans** [comment]
As @decademoon mentioned for DELETE requests you can only set options like {params: {id: 123}} which will be URL encoded `/someurl?id=123`

**Comment by nacr-dev** [comment]
ok, tks for all the help :+1:

**Comment by Rudge** [comment]
Why isn't possible to use one body to request in delete method? By [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.5) there isn't this limitations.
