### ISSUE TITLE
Post sends data under 'body'. BREAKS ANY COMPATIBILITY

### ISSUE THREAD

**Issue by amostajo** [vuejs/vue-resource#339]
The new version has **ZERO** backwards compatibility and behaves not as a **standard** request.

To make this more clear. This:
```
this.$http.post('some/url', formData);
```

Is sending data to the server as:
```
{
    body: formData
}
```

I have to change all my standardized post data retrieval to consider `body` now. Why did you thought this was a good idea?

1) This is not a good practice.
2) This package should act as the standard resource library for Vue. And should be compatible with what ever application is developed for it, with PHP, .NET, Ruby, Node, what ever. YOU CAN NOT FORCE developers to change a standard request retrieval because you though it will be useful, well it isn't.
3) YOU CAN NOT force already developed apps to be refactored because you had your un-genius to un-standardized how things work.
4) Devs have to DEBUG the request sent by this package to figure it out how it behaves, because it is NOT STANDARD.

Without debugging the code and the request, I wouldn't have reliazed that this:
```php
// STANDARD request
$_POST['name'];
```
was being sent as:
```php
// YOU un-genius request
$_POST['body']['name'];
```

Why haven't you though out-of-the-box in this decision?
Why in the sane world you thought this was a good idea?

**I strongly suggest to rollback this change of yours for sake of this package future. If you really want to include body, then make it optional and configurable in the settings. It should NOT, by any mean. be the standard.**

**Comment by amostajo** [comment]
Btw, if you end up deciding to stay with this ridiculous change.

Please, at least modify your **readme** and warn developers that the package doesn't behave standard.

Something like this will work:
> **Projects developed using server code written in PHP, Ruby, .NET and similar will need some additional development efforts to make requests work with this package. This will affect frameworks like Wordpress, Laravel, Symphony, Drupal, CakePHP, CodeIgniter, Zend. Yii, .net., ruby on rails, scorched and similar.**

I hope that with the last quote you can see the negative impact of this change.

**Comment by amostajo** [comment]
Seems that this is the solution:
```
Vue.http.options.emulateHTTP = true;
```

**Comment by LinusBorg** [comment]
... Wow. you should work on your temper.
