### ISSUE TITLE
Why get() method data removed in 0.9.0?

### ISSUE THREAD

**Issue by reefki** [vuejs/vue-resource#341]
Is there any logic reason why the `data` parameter removed from `Http.get()`? in version 0.8.0 I could simply:

```
this.$http.get(this.api, {
    sort: this.sort,
    order: this.order,
    page: this.page,
    query: this.query,
    perPage: this.perPage
})
...
```

Looks clean and readable, but in 0.9.0 up I have to do like this:

```
this.$http.get(this.api + '?sort=' + this.sort + '&order=' + this.order + '&page=' + this.page + '&query=' + this.query + '&perPage=' + this.perPage);
```

Quite messy and unreadable.

**Comment by reefki** [comment]
Another issue in 0.9.* sometimes I need to `JSON.parse` the response data, take a look here https://jsfiddle.net/reefki/b7chzov9/

In version 0.8.0 it's automatically parsed https://jsfiddle.net/reefki/b7chzov9/1/

**Comment by reefki** [comment]
Okay, I found the solution I could pass it as payload:

```
this.$http.get(this.api, {
    params: {
        sort: this.sort,
        order: this.order,
        page: this.page,
        query: this.query,
        perPage: this.perPage
    }
})
```

But still curious why `data` parameter removed.

**Comment by Eden-Sun** [comment]
Look in the README , you should use `response.json()`
```js
new Vue({

    ready() {

      // POST /someUrl
      this.$http.post('/someUrl', {foo: 'bar'}).then((response) => {

          // get status
          response.status;

          // get status text
          response.statusText;

          // get all headers
          response.headers;

          // get 'Expires' header
          response.headers['Expires'];

          // set data on vm
          this.$set('someData', response.json())  <      -----------------

      }, (response) => {
          // error callback
      });

    }

})
```

**Comment by miljan-aleksic** [comment]
I agree with @reefki, it is strange that the data shortcut has been removed but the examples still illustrate it usage, making your above example @Eden-Sun, also wrong as for the params statement.

**Comment by indigoram89** [comment]
please, return data parameter to GET method!!!

**Comment by LinusBorg** [comment]
Why?

**Comment by indigoram89** [comment]
1 - a single interface for all methods - fast and convenient!
2 - no need to keep in mind that with GET-method need to act differently.
3 - do { foo: 'bar' } is not better than { params: { foo: 'bar' } } ?
4 - I now do this throughout the project to look for methods GET and to change them?
5 - what's the point in this change? it has improved?

**Comment by LinusBorg** [comment]
> 1 - a single interface for all methods - fast and convenient!
... not really, this is at least a matter of perspective. 

Odl way: For GET and DELETE, query params to into the data parameter, with POST, PUT, and PATCH, thexy go into `options->params`.

>2 - no need to keep in mind that with GET-method need to act differently.

... see previous point.

> 3 - do `{ foo: 'bar' }` is not better than `{ params: { foo: 'bar' } }` ?

Granted, it's a bit shorter, which is preferable. I would prefer a clean and constistent API though.

> 4 -  I now do this throughout the project to look for methods GET and to change them?

I understand the pain, but vue-resource is <1.0. APIs tend to change in such a state.

> 5- what's the point in this change? it has improved?

API Consistency.

**Comment by indigoram89** [comment]
to be honest, during the development I never used in queries options except for data. this was not necessary. I think most of the developers such a need arises in 1-5% of cases.

therefore, all that has changed for me is the need to write a dozen extra characters.

well what I use abstraction:
clien.post(this.route, this.form)
so I will need to make changes in a few places, but I'm still surprised by this innovation.
