### ISSUE TITLE
credentials bug on IOS7

### ISSUE THREAD

**Issue by Rockergmail** [vuejs/vue-resource#348]
when using credentials on IOS7.0.4, http will add headers below:
Access-Control-Request-Method
Access-Control-Request-Headers

due to the reason above, it turns my method to OPTIONS, but I just want to use POST and send cross origin cookie to server.

**Comment by Rockergmail** [comment]
I test credentials option with jQuery on IOS7.0.4, it is OK

**Comment by lococo--0** [comment]
@Rockergmail conquered?

**Comment by lococo--0** [comment]
@Rockergmail i meet the same problem

**Comment by Rockergmail** [comment]
@lococo--0 Firstable, setting` Vue.http.headers.post={}`; in `main.js` to cover the default header set by author, which will tigger the OPTION method. Secondly, post something like this: 
`this.$http.post(
                        SERVER_API,
                        {
                            data: "just data"
                        },
                        {
                            credentials: true,
                            emulateJSON: true
                        }
                ).then(
                        function (response) {
                           ...
                        },
                        function (response) {
                           ...
                        }
                )`
Last but not the least, don't forget update the vue-resource to the lastest version.

**Comment by lococo--0** [comment]
the OPTIONS method .. em .. puzzled me .. OK .. thx.. i'll try
