### ISSUE TITLE
JSONP

### ISSUE THREAD

**Issue by Zae** [vuejs/vue-resource#35]
The docs make it seem like JSONP is supported, but I'm having problem actually implementing JSONP, I keep getting CORS errors.

Is it actually possible to do JSONP?

**Comment by Zae** [comment]
So I found out how to do a JSONP request, turns out I had to manually change the method to jsonp or simply use the jsonp method that is provided, haha, maybe I should read the docs a bit better.

I thought I should do a get request and by simply providing the jsonp callback it all would start working magically.

**Comment by lensgolda** [comment]
hi! can you show example of your jsonp request?
i do somthing like this, but it won't work:
<code>
this.$http.jsonp('api.vk.com/database.getCountries?need_all=1&count=10', function(data, status, request) {
 callmeback(data);
}, { jsonp: 'callmeback'})
.error(function(data, status, request) {
 console.log(data, status);
 });
var callmeback = function(data) {
console.log(data);
}</code>

**Comment by Zae** [comment]
Hi @lensgolda,

You don't need to call the callback yourself, vue-resource will take care of all of this, it works exactly the same as the get method.

```javascript
this.$http.jsonp('https://api.instagram.com/v1/tags/' + this.hash + '/media/recent', {
    client_id: 'xxxxxxxxxxxxxxxxxxxxxxxx'
}, function(data){
    this.pictures = _map(data.data, this.transFormInstagramModelToLocalModel);
}, {
    'jsonp': 'callback'
});
```

**Comment by lensgolda** [comment]
thanks!

**Comment by milosodalovic** [comment]
@lensgolda @Zae I still can't figure out how to setup jsonp call properly using #1 . I have a login modal window based on Vue that should provide users' ability to login in the middle of some action that requires authentication (social oAuth login). Click on social login button should initiate jsop call toward Laravel API. I have two routes in Laravel API - social auth provider is being contacted, then redirect is made and user data are being picked up by my server. However, I cannot let my front-end know that the action was successful. #1 generates callback function **callback = '_jsonp' + Math.random().toString(36).substr(2),**

**Comment by gkatsanos** [comment]
@Zae does your solution also applies to promises? I am trying : 
```
return Vue.http.jsonp(url, options, {'jsonp': 'callback'}).then((response) => {
      return response.json()
    }).catch(function (e) {
      console.log(e)
      return e
    })
```
but I am getting `vue-resource.common.js?2f13:1272 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0`

**Comment by Zae** [comment]
Hey @gkatsanos, vue-resource has changed a lot since my last reply, I don't think that example is correct anymore.

Try calling the endpoint without that {jsonp: callback} parameter, just do ...jsonp(url,  parameters).then(... and make sure that the api actually returns a correct jsonp reponse.

**Comment by gkatsanos** [comment]
@Zae I am using this API: http://developer.rottentomatoes.com/docs/read/JSON (there's jsonp)

**Comment by gkatsanos** [comment]
This is the request url I see in the network tab:
Request URL:http://api.rottentomatoes.com/api/public/v1.0/lists/movies/in_theaters.json?page_limit=10&page=1&country=us&apikey=123456bcdf&q=&callback=_jsonp63uhb82rgirc54xqmtyr38r529

**Comment by arnabrahman** [comment]
@gkatsanos Have you figured it out how to use jsonp in vue-resource?

**Comment by estufa8** [comment]
Please excuse my bad english.
Open un-minimized `vue-resource.js` code and search for the text `jsonpClient`, you'll see how easy is to follow that code and what it does. Doing that myself I've learnt today that jsonp is nothing more than a hack that consists in creating dynamically a `<script>` element with its `src` attribute pointing to the URL we used in our request. But before sending that request to the server, the lib we use (vue-resource in our case) appends one more parameter named 'callback' with a random generated method name. After this, the server will receive something like: `server.com?name=John**&callback=_jsonpppb7yxl4vjynsy25rb9fnu3di**`. THAT method is the one the server has to write in its response followed by the data enclosed in parentheses. Something like: `return req.params.callback + "('Doe')"`. Say `Doe` say `'(' + JSON.Stringify(myObj) + ')'`.  
That single line of code will be loaded by the browser inside the temp `<script>` element created before, and executed, like any other script the browser loads on page startup. It could return `alert('foo')` and you'd see 'foo' popping in the browser.
Shortening, the server will return **active code** like: `_jsonpppb7yxl4vjynsy25rb9fnu3di('Doo')` which will fall into a <script> element in the browser and get instantly executed. Once done, the vue-resource side will receive the call to that temporary method and process the data to give it to you in the `res` param of your callback (`res.body` to be more exact).
I hope I can shed some light with all this.
