### ISSUE TITLE
this.$http.get(...).error is not a function

### ISSUE THREAD

**Issue by rousos87** [vuejs/vue-resource#351]
Hi guys

I updated to the latest version(0.9.3) and now i have this error :bundle.js:5 Uncaught TypeError: this.$http.get(...).error is not a function.

This is my code

this.$http.get('url', (data) => {
        this.users = data
      })
      .error((err) => console.log(err))

Can anyone help me?

Thanks

**Comment by sqal** [comment]
Your syntax is incorrect, read API documentation https://github.com/vuejs/vue-resource/blob/master/docs/http.md

**Comment by rousos87** [comment]
I already figured it out.thank you btw
