### ISSUE TITLE
 Cannot read property 'ok' of undefined

### ISSUE THREAD

**Issue by pengfu** [vuejs/vue-resource#353]
In some cases, the response get undefined, thus response.ok cause error.
![image](https://cloud.githubusercontent.com/assets/7261281/17479783/2c1a27be-5da7-11e6-80dc-9e5236ee9627.png)

**Comment by callumacrae** [comment]
I had this when I was returning a promise in my `.next()` handler that didn't return a value, eg:

```js
  next((response) => {
    if (response.status !== 401) {
      return;
    }

    return renewAccessToken()
      .then(
        () => Vue.http(request),
        () => {
          logout();
        });
  });
```

To fix it, I just added `Promise.reject()` after `logout()`.

**Comment by callumacrae** [comment]
@blake-newman: Lol, is this undescriptive error intended behaviour?
