### ISSUE TITLE
I can't use "get" with parameters

### ISSUE THREAD

**Issue by elfeffe** [vuejs/vue-resource#354]
This is my code

```
var data = {page: page};
                this.$http.get('api/products', data ).then(
                        function (response) {
                            //look into the routes file and format your response
                            this.$set('items', response.data.data.data);
                            this.$set('pagination', response.data.pagination);

                        }, function (error) {
                            // handle error
                        });
```

I got this from this example https://github.com/JellyBool/laravel-vue-pagination/blob/master/resources/views/welcome.blade.php#L94

But I cant use GET, it doesn't send the parameters. Only clean url (/api/products)
What am I doing wrong?

**Comment by mstaack** [comment]
use post not get!

**Comment by afigienas** [comment]
with ^0.8.0 version it works perfect, but not with ^0.9.3

**Comment by afigienas** [comment]
with 0.9 you need to use params attribute:
``` 
var data = {page: page};
                this.$http.get('api/products', {params:  {page: page}} ).then(
                        function (response) {
                            //look into the routes file and format your response
                            this.$set('items', response.data.data.data);
                            this.$set('pagination', response.data.pagination);

                        }, function (error) {
                            // handle error
                        });
```

**Comment by elfeffe** [comment]
You saved my day :)

**Comment by qida** [comment]
Oh my God ！

**Comment by starock** [comment]
辣鸡，我去找找其他的库。

**Comment by wonderbeyond** [comment]
No clear document about this?

**Comment by anhducbkhn** [comment]
@wonderbeyond it is here: https://github.com/pagekit/vue-resource/blob/master/docs/http.md

**Comment by AnthonyRod** [comment]
thanks man!!!

**Comment by webreinvent** [comment]
In case of ```GET``` this solution is working but not in case of ```POST```, any suggestions?

**Comment by slavensaka** [comment]
Perfect, was looking for this for a month. Thanks @afigienas
`  this.$http.get('api/products', {params:  {page: page}} ).then(
                        function (response) {
                            //look into the routes file and format your response
                            this.$set('items', response.data.data.data);
                            this.$set('pagination', response.data.pagination);

                        }, function (error) {
                            // handle error
                        });`

**Comment by slavensaka** [comment]
Perfect was looking for this answer for a month now.

**Comment by nishajgd** [comment]
My day is saved!! Thank you so much!

**Comment by NielsLucasTrace** [comment]
@webreinvent for POST you just need {someKey: 'someValue'}
