### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: $url

### ISSUE THREAD

**Issue by arccode** [vuejs/vue-resource#36]
I do not use AMD or CMD; after I import vue.js and vue-resource.js , I use Vue.use(VueResource), then Uncaught TypeError: Cannot redefine property: $url; how to resolve this problem? 

error line: 234
 Object.defineProperty(Vue.prototype, '$url', {

**Comment by steffans** [comment]
If you directly import vue.js and vue-resource.js, `Vue.use(VueResource)` is executed automatically by the Vue Resource plugin.

**Comment by arccode** [comment]
@steffans thanks, based on you suggest, vue-resource work fine.

**Comment by PavelPolyakov** [comment]
Hi @steffans , @arccode 

Could you explain, please, how to overcome the issue?
I have it as well, but do not understand the advice.

Here is the part when my app starts:
```javascript
'use strict';

var Vue = require('vue');
var i18n = require('vue-i18n');
var VueRouter = require('vue-router');
var VueResource = require('vue-resource');


var Emitter = require('events').EventEmitter;

// ready translated locales
var locales = {
    'en-US': {
        message: {
            hello: 'the world'
        }
    }
}

// set plugins
Vue.use(i18n, {
    lang: 'en-US',
    locales: locales
});
Vue.use(VueRouter);
Vue.use(VueResource);
// -- end of the plugins setup
```

**Comment by PavelPolyakov** [comment]
I think I just found, that if I use ```vueify``` , then I don't need to connect the *.js files on front-end (including vue.js).

Before I thought that I should.

**Comment by cnweibo** [comment]
I exactly met this issue and fix according to @PavelPolyakov 's advice.
Thanks~!

**Comment by ricardovigatti** [comment]
i have the same error but the solution provided doesn't not work. What i'm missing?

```
// vue-components.js
var Vue = require('vue');

Vue.use(require('vue-resource'));

import ModalForm from '../../components/ModalForm/ModalForm.vue'

new Vue({
    el: 'body',
    components: { ModalForm }
});
```

```
// gulpfile.js
var elixir = require('laravel-elixir');

require('laravel-elixir-vueify');

elixir(function(mix) {
    /**
     * Vue Components
     */
    mix.browserify('vue-components.js', '../../../public/themes/admin/assets/js', 'assets/js');

    [...]
```
