### ISSUE TITLE
Auto refresh a page after 1 seconds

### ISSUE THREAD

**Issue by tisuchi** [vuejs/vue-resource#360]
I am quite new in VueJS. 

I am planning to use VueJS in my laravel chat apps. Currently I am using AJAX to autoload page after 1 seconds. 

Now wondering how can I do auto refresh my page in VueJS after 1 seconds so that users can see all the messages without refresh!

Any clue?

**Comment by steffans** [comment]
This is a userland problem, please try http://forum.vuejs.org
