### ISSUE TITLE
Change log on Releases

### ISSUE THREAD

**Issue by abishekrsrikaanth** [vuejs/vue-resource#37]
@steffans, it would be nice to see the list of important changes that have happened in each of the releases of this repo similar to vue.js repo (https://github.com/yyx990803/vue/releases). It gives the developer an gist of whether there are any important updates that requires one to upgrade or if the new fixes are only new features and good to haves..

**Comment by azamat-sharapov** [comment]
I also think so. Just short explanation would be enough on releases/tags!

**Comment by steffans** [comment]
Good point, i added a changelog on the latest release v0.1.15
