### ISSUE TITLE
0.9.3在部分安卓版微信里不兼容

### ISSUE THREAD

**Issue by lerry** [vuejs/vue-resource#370]
v0.9.3从后端获取数据v-for渲染select option，比如后端返回五条数据，能看到有五个选项，但是option的内容是空的，在iPhone微信上完全正常，使用原生ajax获取数据也正常，切换vue-resource至^0.7.4，也正常。这种情况只在部分版本安卓出现，比如魅族note3 Android5.1 Flyme5.1.35A ，我测试了4部安卓机，三部均为此情况，另外由域名访问转换成ip+端口访问后恢复正常，域名访问使用nginx或者ngrok转发均为同样表现。以上微信均为最新版本

**Comment by lerry** [comment]
response.data 改为 response.json()后正常了，

**Comment by ken1987** [comment]
我也遇到一样的场景，也是通过 response.json()后正常了

**Comment by zhengbowei** [comment]
@lerry 我也遇到这个问题，nginx转发才会出现，ip+端口就没有问题，除了用response.json，新版本的vue-resource可以解决吗？
