### ISSUE TITLE
Square Brackets to HTTP requests been encoded

### ISSUE THREAD

**Issue by caiovisk** [vuejs/vue-resource#371]
Hi there,

I Can`t send square brackets to the URL, the [] in the request is always been encoded.

None of URI Template operators work for square brackets.

Please see the issues: https://jsfiddle.net/g3on09qt/2/ 

Is there any way I can get the  [ ] working?

**Comment by LinusBorg** [comment]
Square brackets are not allowed in URI according to RFC3986

So this has to be handled by your backend correctly - it has to decode the encoded square brackets before pasing the query params on. 

https://tools.ietf.org/html/rfc3986#section-3.2.2

> A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").  **This is the only place where
   square bracket characters are allowed in the URI syntax**.
