### ISSUE TITLE
Ios and Android Get XMLHttpRequest Header Info Uppercase lowercase

### ISSUE THREAD

**Issue by chenli1989** [vuejs/vue-resource#376]
Ios xhr.getAllResponseHeaders() 
![ios](https://cloud.githubusercontent.com/assets/8178749/18083487/e4619cbe-6ed5-11e6-9077-9675b4def4e6.png)

Android  xhr.getAllResponseHeaders() 
![android](https://cloud.githubusercontent.com/assets/8178749/18083496/efa7f6b8-6ed5-11e6-8432-15c6f6cf5aaa.png)

Access to information not do compatibility processing!

![bug](https://cloud.githubusercontent.com/assets/8178749/18083568/495fcd48-6ed6-11e6-8107-5cb2a0c6a809.png)

**Comment by LinusBorg** [comment]
This is fixed in the `dvelop` branch and will be fixed in the next release.

workaround here: #317 

Please consider closing this issue as it is a duplicate.

**Comment by chenli1989** [comment]
Thank you
