### ISSUE TITLE
Request: cancel request

### ISSUE THREAD

**Issue by rleger** [vuejs/vue-resource#38]
It would be nice to be able to cancel an request.

for instance when a user is browsing pages, if he/she clicks to quickly to the next one multiple times the app will keep firing requests. I'd like to be able to only keep the latest active.

Thanks !

**Comment by steffans** [comment]
You could use the `beforeSend` callback to access the request object and a add your code to abort the current request.

```js
this.$http.post('url', function (data) {}, {beforeSend: function(xhr) {
    // use XMLHttpRequest and add xhr.abort callback
}});
```

**Comment by rleger** [comment]
Great, I'll give it a try, thanks

**Comment by rleger** [comment]
Ok, so I'm trying to push the current request to an array of requests. That way, before firing a new one, I can iterate through the all the requests and abort them.

I initialized xhr_request to an empty array on the vue instance.

```
this.$http.get('http://whatever.com', function (data, status, request) {
   // !! data is empty if I this.xhr_request.push(xhr) on the beforeSend callback
}, { beforeSend: function(xhr) {
   for (var i = 0; i < this.xhr_request.length; i++) {
      this.xhr_request.shift().abort();
   }
   this.xhr_request.push(xhr);
}});
```

BUT, when I push the current xhr to the xhr_request array, the returned data object from the request is empty. Chrome inspector shows the expected response from the API. I've tested some scenarios, its definitely pushing xhr to an array that causes the issue. 

Is there something I'm missing ??

Thanks!!

**Comment by rleger** [comment]
After a bit more debugging : 
setting my xhr_requests object globally an not on the vue instance does the trick. I don't fully understand why but it's good enough for now

```javascript
var xhr_requests = [];

new Vue({
...

beforeSend: function(xhr) {
    // Canceled old unfinished requests
    for (var i = 0; i < xhr_requests.length; i++) {
        xhr_requests.shift().abort();
    }

    // Add current request to the queue
    xhr_requests.push(xhr);
}
...
```

**Comment by amirrustam** [comment]
@rleger if you feel like you have a sufficient solution and don't have anything else to add then it's best to close out this issue. Thanks.

**Comment by rleger** [comment]
There you go, sorry.

**Comment by iagafonov** [comment]
beforeSend is renamed to before, as I found out
