### ISSUE TITLE
Server Request is ignoring data parameters

### ISSUE THREAD

**Issue by codebryo** [vuejs/vue-resource#383]
Hello,

I have just upgraded to the latest Version (coming from 0.7) and now the data in a call is completely ignored.

`this.$http.get('/orgs', {name: 'foo'}).then(...)` would generate the url `/orgs?name=foo` but now it just sends `/orgs` with no params any more.

Can't find anything in the docs or release notes about what I could have missed as the examples look the same still.

Help would be very appreciated. Thanks.

**Comment by codebryo** [comment]
I found a workaround, but not sure if this is on purpose: 

```
this.$http.get('/orgs', { params: {name: 'foo'}}).then( ... }
```

This still does the trick.
Should the docs be updated or is this something that needs fixing.

Best,
Roman

**Comment by LinusBorg** [comment]
The docs *are* up to date concerning this:

https://github.com/vuejs/vue-resource/blob/master/docs/http.md

> List of shortcut methods:
> * `get(url, [options])`
> ...

There's no argument that accepts data for a get request, only an options request, and its properties are explained in the linked doc.

**Comment by steffans** [comment]
Yes, the arguments were changed in 0.9+, see changelog https://github.com/vuejs/vue-resource/releases/tag/0.9.0
