### ISSUE TITLE
Cross-origin requests in IE9 always fail

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue-resource#386]
First mentioned here by @soundtina: https://github.com/vuejs/vue-resource/issues/299#issuecomment-240938745

In IE9, any cross-origin request will result in the failure handler being called:

```js
Vue.http({
  method: 'POST',
  url: 'http://my-api/something',
  body: { ... }
})
  .then(
    (res) => { /* this will never be called */ },
    (err) => { /* err is the response, even on 200 */ }
  )
```

`response.ok` is _always_ false: https://github.com/vuejs/vue-resource/blob/master/src/http/index.js#L33

The reason for this is that the `xdr` object doesn't have `status` and `statusText` properties, so these are undefined: https://github.com/vuejs/vue-resource/blob/master/src/http/client/xdr.js#L13-L16

----

So, that's what's causing it. It doesn't look possible to access the status code and text of a response when using the XDomainRequest class: https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest

The most specific we can get is success and failure by having two different handlers. That's the approach taken in [other scripts](https://gist.github.com/michaelcox/2655118#file-xdr-js-L24): that one defaults to 200, and uses the `StatusCode` property from the API response if it is specified.

I'm happy to fix this, but I'm not sure what the best way to fix it is. Giving only 200 and 500 responses leads to unexpected behaviour: for example, a server error will be reported on authentication failure. Having said that, that's better than the current behaviour which is to treat _everything_ as a server failure!

<sup>Is this the reason everyone uses JSONP?</sup>

**Comment by steffans** [comment]
Ok, status 200 or 500 seems like a good compromise. Can you prepare a PR. Thanks

**Comment by callumacrae** [comment]
Thank you! Sorry for not doing this myself - haven't had much time.
