### ISSUE TITLE
 this.$set('someData', data)

### ISSUE THREAD

**Issue by O2M2G23** [vuejs/vue-resource#39]
what is someData??the data which is in my <code>.json</code>file? or the data which is in my Vue instance? i am new at this.

**Comment by rleger** [comment]
someData is the name of the property of the vue instance you want to store your results on.

data is the response from the request.

```
new Vue({
  el: 'body',
  data: {
    someData: []
  }
}
```

**Comment by O2M2G23** [comment]
<pre>
new Vue({
    el:'body',
    data:{
        someData:[]
    },
    ready:function(){
        this.$http.jsonp('url',function(data,staus,request){
			this.$set('someData',data)
		}).error(function(data,staus,request){
		})
	}
}
</pre>
this is my code
but when i use the browserify
it's wrong :(
