### ISSUE TITLE
some bug with promise(1.0.x)

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs/vue-resource#396]
this.$http.get('xxxx').then((res) => {
      return 'a string';
}).then((str)=>{
   console.log(str)
}).catch((err)=>{
   console.log('catch some err')
})
it always console.log('catch some err')  over 1.0.x,
but console.log(str) on v0.9.3

**Comment by yuu2lee4** [comment]
i find reason ， response.json() return a promise and it returned a json Object before.

**Comment by steffans** [comment]
Yes, this was a API change in 1.0, you can use `response.body` instead which contains the parsed json object.

**Comment by yuu2lee4** [comment]
res.body confused me, it sometimes get a json Object, and sometimes get a json string .

**Comment by hezhongfeng** [comment]
@yuu2lee4 
the same problem.
