### ISSUE TITLE
HTTP response header parsing is case-sensitive

### ISSUE THREAD

**Issue by jeffturcotte** [vuejs/vue-resource#397]
I was using vue-resource with a remote API that returned responses with HTTP headers in all lowercase. This greatly confused the parsing of the json data due to this case-sensitive check: https://github.com/vuejs/vue-resource/blob/master/src/http/interceptor/body.js#L40. i.e. 'content-type' was not found when looking for 'Content-Type'. Because of this, the data was parsed as a string, leading to some extremely bizarre behavior with my Vue components.

**The HTTP standard says that header names are case-insensitive so this library should be modified so they are matched that way.**

I was able to fix my own issue with a hacky proxy that normalized the HTTP headers to the more common (and better) format using this lib: https://github.com/marten-de-vries/header-case-normalizer. 

I can implement a fix/test if I can get a little guidance as to where in the library such normalization should be placed.

Thanks!

**Comment by steffans** [comment]
Thanks, with the latest v1.0+ the headers are matched case-insensitive.
