### ISSUE TITLE
[Feature] Global Error Handler

### ISSUE THREAD

**Issue by underparnv** [vuejs/vue-resource#40]
Would be cool to have as part of the data an errorHandler that gets called on any HTTP error returned, globally.

As an example: https://github.com/zerqu/qingcheng/blob/master/lib/xhr.js#L67

Would be super handy...

**Comment by underparnv** [comment]
Nevermind...  `Vue.http.options.error` is already a thing. Ignore me today. ;)

Thanks for the great work!

**Comment by underparnv** [comment]
Maybe I'm mistaken. I've added Vue.http.options.error and it does trigger, but so does the success callback, even on a 500 error from the server.

https://github.com/vuejs/vue-resource/blob/master/src/http.js#L155

Maybe just technical assistance is needed here... ;)

**Comment by JosephSilber** [comment]
Once we get [a proper response intercepting pipeline](#5), you'll be able to do this.

**Comment by underparnv** [comment]
Closing as dupe of #5
