### ISSUE TITLE
Strange issue with Chrome

### ISSUE THREAD

**Issue by brunjick** [vuejs/vue-resource#402]
So, I decided to switch to SSL on my production server and everything seemed to work properly, unless I enabled http/2 in nginx conf. Problem is that json responses aren't parsed at all, and this happens only on latest Chrome builds. I'm using `response.data` property to get response in json format, is this a wrong way? Right now I just added interceptor to convert responses and it works fine
```js
Vue.http.interceptors.push((request, next)  => {
  // continue to next interceptor
  next((response) => {

    // modify response
    response.data = JSON.parse(response.data);

  });
});
```

**Comment by LinusBorg** [comment]
You probably encounter #317. This was fixed in 1.0

**Comment by brunjick** [comment]
@LinusBorg thanks, most likely you are right, I'm using 0.9.3.

BTW, is there any performance difference between `response.json()` and `response.data` when response is json anyway? because I already switched to `response.json()`.

**Comment by LinusBorg** [comment]
Probably not, as the pasting method is the same and currently, your response is not parsed automatically due to the bug. 

So you do the same as the lib would do for you when you use json()

**Comment by LinusBorg** [comment]
PS: can you close the issue if that answer is sufficient?

**Comment by brunjick** [comment]
@LinusBorg Thanks
