### ISSUE TITLE
emulateJSON for resource

### ISSUE THREAD

**Issue by azamat-sharapov** [vuejs/vue-resource#41]
How can I set `emulateJSON` to true for particular request like:

```javascript
resource.update({id: id}, data) // .then(...).catch(...)
resource.save(data) // .then(...).catch(...)
```

I've been looking into [source](https://github.com/vuejs/vue-resource/blob/master/src/resource.js#L40), if I'm not mistaking, I can't pass those options here. 
Note: I can't to use `vm.$http`, as this code is outside of vm and want to also avoid setting it globally: `Vue.http.options.emulateJSON = true`.

Thanks

**Comment by steffans** [comment]
Yes, its not possible to pass this option. The resource, factory function needs to be updated to allow passing a options object.

**Comment by steffans** [comment]
Supported in v0.1.17 and above, by passing options to `this.$resource(url, [params], [actions], [options])`

**Comment by azamat-sharapov** [comment]
Danke @steffans!
