### ISSUE TITLE
Interceptor Documentation: Setting Headers

### ISSUE THREAD

**Issue by derekolson** [vuejs/vue-resource#412]
The documentation for setting headers in an interceptor is incorrect. Looking through the interceptor source, I noticed that you set headers by using `request.headers.set(name, value)`

https://github.com/vuejs/vue-resource/blob/master/src/http/interceptor/method.js#L8

**Comment by httpoz** [comment]
Thank you for the solution @derekolson was struggling with this after updating from 0.9
