### ISSUE TITLE
bodyText  undefined

### ISSUE THREAD

**Issue by Creabine** [vuejs/vue-resource#418]
I get response Obj,  but the bodyText is undefined.
![image](https://cloud.githubusercontent.com/assets/17755176/18710329/4c453d0a-8037-11e6-91ee-e545bf06c781.png)

**Comment by Creabine** [comment]
so i can't use the    response.json()        to get Obj,plz help...T.T

**Comment by steffans** [comment]
Try `response.body`to get the JSON object.

**Comment by Creabine** [comment]
thx~
