### ISSUE TITLE
when I use 'jsonp',navigator console error 'Uncaught SyntaxError: Unexpected token :'

### ISSUE THREAD

**Issue by githubmann** [vuejs/vue-resource#419]
Here is my code 
this.$http.jsonp('http://news-at.zhihu.com/api/4/news/latest',{ 'jsonp': 'callback' }).then(function (res) { console.log(res) })
Here is the error tip

![](https://cloud.githubusercontent.com/assets/10526614/15532394/2747518a-2292-11e6-8730-9368c7c3b6ac.png)

**Comment by githubmann** [comment]
#278

**Comment by Sioxas** [comment]
same problem

**Comment by gkatsanos** [comment]
same problem.

**Comment by StKostya** [comment]
already 2018, but the problem remained
