### ISSUE TITLE
it's a suggestion : enable a head request in vue-resource

### ISSUE THREAD

**Issue by JJ2667699** [vuejs/vue-resource#426]
would u mind add head in Resource.actions ? like this 
`
Resource.actions = {
    head: {method: 'HEAD'}}
`

so we can use 
`
Vue.http.head('http://cclcupload.b0.upaiyun.com/nationalDay/208327147487337608569391.jpg')
`
to just get response status,this can help us avoid some 404 cache from CDN Services

**Comment by steffans** [comment]
When creating a resource you can add your own custom actions, see https://github.com/vuejs/vue-resource/blob/master/docs/resource.md#custom-actions

**Comment by websanova** [comment]
I'm having same issue, and this example doesn't seem to work. Do you have a direct sample for HEAD request?
