### ISSUE TITLE
this.$http.get does not work in IE9 

### ISSUE THREAD

**Issue by CXHtml** [vuejs/vue-resource#43]
Hi, I just simply use this method to load async data from cross site domain, it successfully works in Chrome(44.0.2403.157), safari(8.0.7 (10600.7.12)), firefox(39.0.3) and IE 11 to 10(including the default edge mode), but in IE9,  the running code just jump into the '.error(function(){})' code block, as a result I got an error info. I'm not sure is something wrong with my code or just the $http.get method does not support IE 9?

**Comment by azamat-sharapov** [comment]
I think it's about Promise support: http://caniuse.com/#feat=promises

**Comment by CXHtml** [comment]
Finally, I found the problem is that IE9's browser doesn't allow cross site domain access by default when you make ajax request. So the solution is to turn off the XSS Filter in IE browser manually, so it's not the $http.get problem.

**Comment by kobezone** [comment]
turn off the XSS Filter in IE browser manually do not work any other resolve action?

**Comment by rocky-191** [comment]
有没有什么兼容的办法

**Comment by piyushSinghalDemo** [comment]
same issue still facing in IE EDGE.., trying to find a way to fix it
