### ISSUE TITLE
Shortcut methods do not work

### ISSUE THREAD

**Issue by mediafreakch** [vuejs/vue-resource#433]
As described in the docs I'm doing:

```
var Vue = require('vue');
var VueResource = require('vue-resource');

Vue.use(VueResource);
```

After that I would like to use `Vue.http` inside a store. But the method contract is not what docs describe. If I do: `console.log( Vue.http.get )` it returns: `function (url, data, success, options) { ... }`

I'm expecting something like `function (Http(url, options) {}`

Using vue and vue-resource in a browserify environment...

**Comment by LinusBorg** [comment]
Well, the `.get` property returns a "curried" version of http, e.g. with `options.method` set to 'GET' ...

You say shortcut methods do not work - can you show an example of how you try to use them and what you would expect to happen, but doesn't?

**Comment by mediafreakch** [comment]
I'm trying to use it as described in the [docs](https://github.com/vuejs/vue-resource/blob/master/docs/http.md) :

```
Vue.http.get('localhost:8085/api/user', { headers: { 'Authorization': 'Bearer: 123' } })
   .then(function () {
        console.log('yes')
    }, function (response) {
        console.log('ooops')
    })
```

I expect the Authorization header to be added to the request. Instead it forms this request:
`localhost:8085/api/user?headers%5BAuthorization%5D=Bearer%3A+123`

**Comment by LinusBorg** [comment]
You are probably using an outdated version.

Previous versions had a different argument signature for `get`:

`.get(path, data, options)`

now it's similiar to the others:

`.get(path, options)`

**Comment by mediafreakch** [comment]
Ups. Was using 0.8.0. How dumb.
