### ISSUE TITLE
vue-resource doesn't work in vuejs 2.0

### ISSUE THREAD

**Issue by david30xie** [vuejs/vue-resource#437]
I am using vuejs 2.0. full code please see https://daimaduan.com/paste/5b0191d9538

I cannot even see 'hello' in console. did I do something wrong?

**Comment by HashemQolami** [comment]
@david30xie `ready` hook is deprecated in Vue v2. Try using `mounted` hook instead. Further info: http://vuejs.org/guide/migration.html#ready-deprecated

**Comment by david30xie** [comment]
Oops.
Got it now. Thank you @HashemQolami
