### ISSUE TITLE
Done method

### ISSUE THREAD

**Issue by pdcmoreira** [vuejs/vue-resource#45]
Hello,

I'm trying to call a method on `this.$http.post` when the request has received a response, wether it has been successful or not.

I've tried `this.$http.post(...).done(function(data, status) {});` but it doesn't work:
`Uncaught TypeError: this.$http.post(...).error(...).done is not a function`

Is there any way to achieve this?

**Comment by azamat-sharapov** [comment]
https://github.com/vuejs/vue-resource#example

**Comment by pdcmoreira** [comment]
@azamat-sharapov There are the methods "success" and "error", but there is no method "finished" or "done" where I can put the code that must run whether the request has been executed successfuly or not. Check "jqXHR.done()" method from jQuery.

**Comment by azamat-sharapov** [comment]
There is [always()](https://github.com/vuejs/vue-resource/search?utf8=✓&q=always) method.

**Comment by pdcmoreira** [comment]
Ok, amazing! :+1:
