### ISSUE TITLE
TypeError problem when running in production

### ISSUE THREAD

**Issue by bhdryaman** [vuejs/vue-resource#450]
I have started to use VueJS. I build default skeleton with "**vue init webpack my-project**". I added "**vue-resource": "^1.0.3**" and other dependecies. Then everthing run nice in development mode with webpack. i decide to run it in server and after the command "**npm run build**" and the page in server isnot ok because there is a error in console "**vue-resource.common.js:280 TypeError: Cannot read property 'replace' of null**".

**Comment by bhdryaman** [comment]
I found the the source of issue that is the variable **csrfCookie** below. 
it should be added the one control before it and it start to run again corectly...

**Vue.http.headers.common['X-CSRFToken'] = csrfCookie**

**Comment by lanbaba** [comment]
我也碰到这个问题，我的问题出在interceptors上，不能在除了post、put、delete以外的请求上加Header参数，正确的写法如下（ES6环境）：

let result = ['post', 'delet', 'put'].find((item) => item === request.method.toLowerCase());
if(result){
     let token = getCookie('sessionToken'); 
     Vue.http.headers.common.Authorization = token;
 }
