### ISSUE TITLE
调用post或get函数为什么会发起2次请求？

### ISSUE THREAD

**Issue by djjandyhl** [vuejs/vue-resource#456]
this.$http.post(this.$root.apiRoot+'admin/login/doLogin',this.form).then((res) => {
                if(res.data.code != 1){ 
                  this.$message({ 
                    message: res.data.msg, 
                    type: 'error',
                    showClose: true
                  });
                }
            })
chrome里调试同时出现了2次dologin的请求：
第1条发起人是<vue-resource.common.js?e289:1071>，使用post时，没有带上参数
第2条发起人是<other>，使用post时，这一条会带上参数。
是什么情况导致的啊。
我确定这个方法只执行了一次，因为console只输出了一次‘submit’

**Comment by djjandyhl** [comment]
好像是跨域引起的。。。

**Comment by dinfer** [comment]
是跨域引起的。

浏览器发起跨域请求分两种：一种是simple，另一种需要preflight。如果进行preflight了，你就会看到两次请求，一个OPTION，另一个就是你的跨域请求。

总的来说就是你的请求浏览器不知道是否被允许，需要发送OPTION请求提前查看下。prefight参见[MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests)

**Comment by djjandyhl** [comment]
谢谢。

**Comment by helios741** [comment]
@dinfer 使用fetch的话，第一的请求被catch住了，但是第二次的请求是谁发起的呢？
![image](https://user-images.githubusercontent.com/12036324/39407785-54dcc4f8-4bfe-11e8-8d57-5b1d9da39593.png)

请求如下图：
![image](https://user-images.githubusercontent.com/12036324/39407787-6f37be5c-4bfe-11e8-910a-c285226cba32.png)
