### ISSUE TITLE
Update docs to state that IE9 is not supported.

### ISSUE THREAD

**Issue by nivv** [vuejs/vue-resource#46]
I'm trying to make a request from my Vue-script to the same domain but IE9 won't allow it. See issue #43 

I think the docs should be updated so other people doesn't make the misstake as me, thinking it would work.

I've made JS-bin with the problem.
http://jsbin.com/bafeco/edit?html,output

Edit:
Seems like SuperAgent suffers from this as well. Is there a work around? Asking the user to disable the XSS filter isn't the best idea I'm guessing

Edit 2: 
Tried disabling XSS-filter in IE9, still doesn't work. Also tried setting CORS to allow all origins just in case on my api endpoint. Same problem

**Comment by steffans** [comment]
Seems like `XDomainRequest`can be used in IE9, https://developer.mozilla.org/de/docs/Web/API/XDomainRequest to work fix this issue.

**Comment by nivv** [comment]
@steffans Sorry for the late response, but no, it's the same issue.

**Comment by steffans** [comment]
@nivv Can you try the latest v0.1.16, this should work in IE9

**Comment by davidhund** [comment]
I am running into issues with IE9 cross-domain `XDomainRequest` (XDR). It does not seem to work 'out of the box' in 0.1.16.

I am aware of many issues with CORS XDR in IE9, but I was under the impression vue-resource dealt with those?

When I simply use 'plain' XDR for IE9, it works in my case: https://jsfiddle.net/exuezbw5/

Seeing that my 'plain' XDR works (in my case) and vue-resource uses supports XDR it seems this would be easy to fix? Is there some setting I am forgetting?
