### ISSUE TITLE
OPTIONS instead of GET,POST.. 

### ISSUE THREAD

**Issue by keroumi** [vuejs/vue-resource#47]
Hello,

I think I'm getting Options instead of GET or POST because of some CORS issues, how can I prevent this? 

Thanks.

**Comment by mashuble** [comment]
I have the same issue

**Comment by vedraan** [comment]
OPTIONS is always fired first if you're not sending requests to the same domain, so if you're server is not handling OPTIONS or doesn't have proper allow origin settings there, the GET/POST will never be sent.
It's not a bug, it's how CORS works. You would see the same thing if using angular/react or any other AJAX framework.
