### ISSUE TITLE
Got 'response.body.json is not a function' while using vue2.0

### ISSUE THREAD

**Issue by david30xie** [vuejs/vue-resource#470]
I wrote a really simple app to just test vue 2.0 + vue-resource 1.0.3, however I got an error says 'response.body.json is not a function' in console.

key part of code:
```
export default {
  data () {
    return {
      comments: []
    }
  },
  mounted () {
    this.$http.get('http://localhost:3000/api/comments').then(
      (response) => {
        this.comments = response.body.json()
      },
      (response) => {

      }
    )
  }
}
```

Did I do anything wrong here?

P.S. In case you need my repo: https://github.com/david30xie/vue-test

**Comment by wb9688** [comment]
Yes, you should do `response.json()`…

**Comment by david30xie** [comment]
@wb9688
thank you for reply.

I did what you said, and new error just came out: `vue.js?3de6:2252 Uncaught TypeError: Cannot read property 'text' of undefined`

**Comment by david30xie** [comment]
@wb9688 I figured out that I can just use `response.body`

**Comment by reiz** [comment]
Thanks @david30xie your response helped me.
