### ISSUE TITLE
jsonp can't return data

### ISSUE THREAD

**Issue by neciszhang** [vuejs/vue-resource#473]
i use the jsonp methods like this:

```
 this.$http.jsonp("http://news-at.zhihu.com/api/4/news/latest").then(
                  (response) => {console.log(response)},
                  (response) => {alert(response.json()); }
                );
```

but it return error : 
![image](https://cloud.githubusercontent.com/assets/16221107/19713545/8bb332d2-9b79-11e6-895a-1f5232b099fa.png)

**Comment by echopi** [comment]
it seems like that this `http://news-at.zhihu.com/api/4/news/latest` api  just not support jsonp.

try this:

```
http://news-at.zhihu.com/api/4/news/latest?callback=abc
```

**Comment by ICTlight** [comment]
Have you deal this problem? The same with you...

**Comment by dean5277** [comment]
jsonp can not support post method.

**Comment by neciszhang** [comment]
yeah  ,the api  is not  support JSONP method,  but it is support post/get method ,i  use the proxy to 
solve the problem,

**Comment by benjides** [comment]
Calling the `GET` method and passing the JSONP callback name as a parameter seems to do the trick for me.
Here is a working example:
```
Vue.http.get('api', {
      params: {
        callback: 'callback'
      }
    })
    .then((response) => {
      console.log(response.data)
    })
```
Note it does not matter the callback name as the library would parse it automatically into a JSON object.
