### ISSUE TITLE
When root url defined, get method doesn't accept data

### ISSUE THREAD

**Issue by dennisver** [vuejs/vue-resource#49]
When I define the root url globally;
```
Vue.http.options = {
  root: 'http://...'
};
```

The get method doesn't accept data anymore.
```
this.$http.get('endpoint', { foo: 'bar' })
```
Error: **Cannot set property 'foo' of undefined**

Working JSFiddle: http://jsfiddle.net/wzopw800/1/
Non-working JSFiddle: http://jsfiddle.net/wzopw800/ (see console)

**Comment by limichange** [comment]
https://github.com/vuejs/vue-resource/issues/49

**Comment by dennisver** [comment]
@limichange In your JSFiddle, data is the response of the request. Or am I wrong? Instead, I'd like to pass some data to the request.

**Comment by limichange** [comment]
@dennisver Yes, data is the response of the request, and see http://jsfiddle.net/sgzwojhg/4/.

**Comment by kcalliauw** [comment]
preceding / in the relative URI has to be omitted when using the root option. The framework inserts that automatically.
http://jsfiddle.net/oskoueny/

**Comment by dennisver** [comment]
Thanks @kcalliauw

**Comment by dennisver** [comment]
@kcalliauw Leaving the / doesn't solve the issue in your JSFiddle. The way you set your root does.
Why exactly is that?

```javascript
// works
Vue.http.options.root = 'http://httpbin.org';
```
```javascript
// doesn't work
Vue.http.options = {
  root: 'http://httpbin.org'
}

Maybe using this method removes all other properties of Vue.http.options

**Comment by steffans** [comment]
@dennisver Yes, you need to modify the options this way, otherwise all default options will be removed. Also make sure to use a relative URI, only then the root will be prepended.
```javascript
// works
Vue.http.options.root = 'http://httpbin.org';
```
See updated: http://jsfiddle.net/wzopw800/2/
