### ISSUE TITLE
Request: modify response

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-resource#5]
Not sure if possible, but I would like the possibility to alter the response content before is returned, similar to the beforeSend callback. The main purpose is to alter the response when performing tests.

**Comment by JosephSilber** [comment]
Similar to Angular's [request/response interceptors](https://docs.angularjs.org/api/ng/service/$http#interceptors)?

That would be awesome!

**Comment by Fauxide** [comment]
:+1:

**Comment by JosephSilber** [comment]
@steffans would you be interested in a feature like this? If so, I can try taking a stab at it...

**Comment by Fauxide** [comment]
Thanks @JosephSilber, I really hope something like this gets implemented

**Comment by steffans** [comment]
@JosephSilber Like the idea of interceptors, Angular supports this concept. I also want to have a look at their implentation, before developing a API for this feature.

**Comment by Fauxide** [comment]
@steffans Any news on this? This is *very* useful for cleanly handling cases where a server returns 5xx error codes (ie. a user is not logged in etc)

**Comment by underparnv** [comment]
:+1: on this feature, would be amazing.

**Comment by warksit** [comment]
![image](https://cloud.githubusercontent.com/assets/5296633/10073040/fb82ad4a-62bd-11e5-9ce1-b2f763016612.png)

**Comment by kcalliauw** [comment]
+1 for this. Having to check -everywhere- for a 401 and returning the user to the login route is a pain. Interceptors would be a welcomed addition.

**Comment by jorgemurta** [comment]
+1

**Comment by kcalliauw** [comment]
FYI: I switched to rest.js because of this for vue-starter. If anybody's interested, I implemented a custom interceptor there. You can check out the code here: https://github.com/layer7be/vue-starter

That being said, it would still be nice to have this functionality available in vue-resource.

**Comment by ryanwinchester** [comment]
+1

**Comment by andrewdavidcostello** [comment]
+1

**Comment by ryanwinchester** [comment]
@JosephSilber if you do this, you would be my new hero (for at *least* a month)

**Comment by steffans** [comment]
@ryanwinchester Take a look at the dev branch, there is implementation im working on.

**Comment by ryanwinchester** [comment]
@steffans that's exciting!

is the develop branch working? i.e. can i require it in my package.json and not blow up my app too bad?

if not, do you have an estimation of when we can expect a release with this that's useable? 🙏

thanks so much for all your work

**Comment by znck** [comment]
@steffans release?

**Comment by steffans** [comment]
@ryanwinchester Please try out the develop version and let me know how the interceptor feature works for you. 

@znck The headers are right now missing from the response object. I still need to add a parser for the headers.

**Comment by miljan-aleksic** [comment]
@steffans, I am able to alter the request/response with the interceptor, nice! What I'm not able is to identify the response I'm editing. That makes not impossible intercepting different responses in the same page. The solution could be sending the request object along the response, which is [right there](https://github.com/vuejs/vue-resource/blob/develop/src/interceptor/index.js#L18).

Am I missing something?

**Comment by steffans** [comment]
@miljan-aleksic Ok, i just added the current request to the response object.

**Comment by miljan-aleksic** [comment]
Thanks!

**Comment by ryanwinchester** [comment]
I am working on a deadline so still using another library but hopefully next week I can play with the interceptors in vue-resource!

thanks @steffans

**Comment by hfalucas** [comment]
Hi @steffans this feature would be awesome. Meanwhile I saw that you have it implemented on the develop branch so I can start testing it right away and give you some feedback.

Can I install the develop branch through npm?

**Comment by miljan-aleksic** [comment]
@hfalucas, yes, you can, even with bower, you would just have to reference the full git url for NPM or just "develop" for bower. I have tested it and so far, good, but more feedback would be appreciated.

**Comment by hfalucas** [comment]
Thanks @miljan-aleksic. I'm referencing it like this: `"vue-resource": "git://github.com/vuejs/vue-resource.git#develop"` but it is failing when installing because of this: `webpack --config build/webpack.build.config.js`. Anyway I will just download the file and then require it so I can start use and give some feedback :)

**Comment by matisoffn** [comment]
Does anybody have a good, working example of globally intercepting responses to check if the server returns 403/401 so that the user can be signed out?

**Comment by ryanwinchester** [comment]
@hfalucas i had the same problem.

just waiting for this to be merged and tagged, i guess.

**Comment by steffans** [comment]
Available in v0.5.0.

**Comment by NicolasParada** [comment]
Nice

**Comment by plakhin** [comment]
Using 0.6.1 and still can not understand how to get response headers.
@steffans , could you please provide some info?
Thanks

**Comment by dominikveils** [comment]
@plakhin have the same problem. Do you found any solution?

**Comment by znck** [comment]
Your can access header with `headers` method on response object. 
```js
Vue.http.get('/foo').then((response) => {console.log(response.headers())})
```
You may have to whitelist which headers can be accessed. (Mostly in case of cross-domain requests.)
For example, I have a CORS middleware on my Laravel app to this header to every response.
`Access-Control-Allow-Headers: X-Requested-With, X-Auth-Token, Authorization, Accepts, X-CSRF-TOKEN`

**Comment by dominikveils** [comment]
@znck thank you. Thats what I need.

**Comment by huchun666** [comment]
thanks
