### ISSUE TITLE
Global configuration of vueJS

### ISSUE THREAD

**Issue by Clebiez** [vuejs/vue-resource#50]
Hi,

I'm a beginner in VueJS and, after many times on Google i can't found any solution :
When i want to configure vue-resource in global like that : (app.js file)
```javascript
Vue.use(VueResource);
Vue.http.options.root = 'http://127.0.0.1:1337';
Vue.http.headers.common['Authorization'] = 'Basic YXBpOnBhc3N3b3Jk';
```

Webpack don't like me at all, why ?

Thanks for your help !

**Comment by gil0mendes** [comment]
Same here... I really need a solution for that :(

**Comment by gil0mendes** [comment]
After all the error it's mine... When we use a '/' in url like that `this.$http.get('/post', ...)` the root config isn't used... The vue-resource only use the root config when the slash isn't present at first position in the url.

**Comment by dinghua** [comment]
@gil0mendes your are the man!

**Comment by mattjdev** [comment]
That _seriously_ needs to be documented somewhere! (Other than this issue)...

**Comment by smolinari** [comment]
Documentation PRs are easy to do! :smile: 

Scott
