### ISSUE TITLE
Each request sends an OPTION request before the actual request

### ISSUE THREAD

**Issue by kfirba** [vuejs/vue-resource#57]
Hello.

I've noticed that each request sends an OPTION request before the the actual request. Why is that? I don't want to send an OPTION request before each request I want to make.. that only adds to the time it takes for the actual request and seems redundant.

How can I disable it?

**Comment by kfirba** [comment]
Okay, apparently this has nothing to do with Vue-resource but with CORS.

**Comment by junerockwell** [comment]
@kfirba How did you fix it?

**Comment by JoshuaDoshua** [comment]
@junerockwell , it is not something you can fix. Suffering through cors issues myself..
Anytime you make a request to a different URL it will send an OPTIONS request first. This is a part of CORS functionality. Read more here:
http://www.html5rocks.com/en/tutorials/cors/
